GoogleCloudPlatform/terraformer

README.md
cmd/import.go
cmd/openstack.go
go.mod
go.sum
openstack_terraforming/compute.go
openstack_terraforming/networking.go
openstack_terraforming/openstack_provider.go
openstack_terraforming/openstack_service.go
tests/openstack/main.go

This PR adds support [OpenStack provider](https://www.terraform.io/docs/providers/openstack/). Currently this provider supports the following resources:
* Compute
* [compute_instance_v2](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html)
* Networking
* [networking_secgroup_v2](https://www.terraform.io/docs/providers/openstack/r/networking_secgroup_v2.html)
* [networking_secgroup_rule_v2](https://www.terraform.io/docs/providers/openstack/r/networking_secgroup_rule_v2.html)

Support OpenStack provider

---

gcp_terraforming/gcs.go

GCP provider checks "role_entity" attribute for retrieving GCS ACL.
https://github.com/terraform-providers/terraform-provider-google/blob/d43a1795b4c1ee45d15d83ba33b588448f3ff392/google/resource_storage_bucket_acl.go#L202
This PR adds "role_entity" to attributes of google_storage_bucket_acl.

google: Add role_entity to google_storage_bucket_acl

---

providers/aws/route53.go

providers/aws/route53.go
https://golang.org/pkg/strings/#TrimPrefix
TrimPrefix returns s without the provided leading prefix string. If s doesn't start with prefix, s is returned **unchanged**. Therefore It is unnecessary to check with `strings.HasPrefix`

Replace if statement with an unconditional strings.TrimPrefix in aws/route53

---

README.md
cmd/aws.go
cmd/github.go
cmd/google.go
cmd/import.go
cmd/kubernetes.go
cmd/openstack.go
terraform_utils/service.go

Add filter options. We can import resource by IDs and not all.
syntax for flag small complicate 
```
--filter=TERRAFORM_TYPE1=ID_OF_RESOURCE1:ID_OF_RESOURCE2
--filter=TERRAFORM_TYPE2=ID_OF_RESOURCE4:ID_OF_RESOURCE3
```
example
```
--filter=google_compute_firewall=jenkins1:ssh
--filter=google_compute_network=stage:productions
```
TODO use regex

Add filter options

---

providers/aws/route53.go
providers/gcp/monitoring.go

linter(golangci-lint) said
```
providers/aws/route53.go:61:9: nilness: impossible condition: nil != nil (govet)
if err != nil {
^
providers/gcp/monitoring.go:49:9: nilness: impossible condition: nil != nil (govet)
if err != nil {
^
```
https://github.com/GoogleCloudPlatform/terraformer/blob/9bc5fe1add8a73bc4ba12d08d69bebc2bc0e5162/providers/aws/route53.go#L37-L66
e.g.  createZonesResources is unreachable condition in L61 because It has return on L41 when err is not nil, and L45-L60 hasn't change the value of err.

Fix nilness: impossible condition: nil != nil

---

README.md
providers/aws/acm.go
providers/aws/aws_provider.go

This PR adds ability to import AWS Certificate Manager certificate resource (`aws_acm_certificate`).
The exported HCL and state file will look like following:
```hcl
resource "aws_acm_certificate" "01234567-89ab-cdef-0123-456789abcdef_example--com" {
domain_name               = "*.example.com"
subject_alternative_names = ["*.foo.example.com"]
tags                      {}
validation_method         = "EMAIL"
}
```
```json
{
"version": 3,
"terraform_version": "0.11.12",
"serial": 1,
"lineage": "01234567-89ab-cdef-0123-456789abcdef",
"modules": [
{
"path": [
"root"
],
"outputs": {
"aws_acm_certificate_01234567-89ab-cdef-0123-456789abcdef_example--com_id": {
"sensitive": false,
"type": "string",
"value": "arn:aws:acm:us-east-1:012345678910:certificate/01234567-89ab-cdef-0123-456789abcdef"
}
}, …
```

Add aws_acm_certificate support

---

README.md
providers/datadog/datadog_provider.go
providers/datadog/downtime.go
providers/datadog/user.go

This PR add support for Datadog provider.
- supported resources
- [datadog_downtime](https://www.terraform.io/docs/providers/datadog/r/downtime.html)
- [datadog_user](https://www.terraform.io/docs/providers/datadog/r/user.html)

Add support datadog user and downtime resources

---

README.md
providers/datadog/datadog_provider.go
providers/datadog/synthetics.go

This PR add support for Datadog provider.
- supported resources
- [datadog_synthetics_test](https://www.terraform.io/docs/providers/datadog/r/synthetics.html)

Add support datadog_synthetics_test resource

---

README.md
providers/datadog/datadog_provider.go
providers/datadog/screenboard.go
providers/datadog/timeboard.go

This PR add support for Datadog provider.
- supported resources
- [datadog_screenboard](https://www.terraform.io/docs/providers/datadog/r/screenboard.html)
- [datadog_timeboard](https://www.terraform.io/docs/providers/datadog/r/timeboard.html)

Add support datadog dashboards resource

---

README.md
cmd/aws.go
cmd/datadog.go
cmd/github.go
cmd/google.go
cmd/import.go
cmd/kubernetes.go
cmd/openstack.go
cmd/plan.go
cmd/root.go
terraform_utils/resource.go

⚠️ **This PR is a feature proposal.** Codes/implementation may not be clean/intelligent enough.
---
This PR adds two new commands:
```
terraformer plan <provider> ...
```
and:
```
terraformer import plan <planfile>
```
The first command generates a JSON file (_planfile_) that contains a list of resources that Terraformer retrieved.
Then the second command loads the generated planfile, and generates `.tf` and `.tfstate` files.
This makes users able to review the retrieved resources, and edit them to rename the resources before generating `.tf` files, or filter the resources to only what they needed.
This is especially useful if the user had a huge number of resources on the cloud provider and they wouldn't want to import all of them at one time, but some.
I believe this feature is really …

Proposal: Adding a "plan" feature

---

terraform_utils/utils.go

Refresh may take long time depending on the number of resources and stability of network connection. For instance in my case it hangs up for tens of minutes at refreshing step.
This commit let refresh show which resource are being imported so users can see it's still in progress.
Thread safety: [logger is simultaneously writable](https://golang.org/pkg/log/#Logger) so it would cause no problem in goroutine loop :)

Log refreshing status

---

cmd/import.go

I accidentally removed `import plan` subcommand at e4d975b 😭
This commit re-adds it. My apologies.

Re-add `import plan` command

---

providers/aws/route53.go

Querying AWS Route 53 Record [internally requires `SetIdentifier`](https://github.com/terraform-providers/terraform-provider-aws/blob/5daf292b7bfece60a41e65165a2cd77afa017fc6/aws/resource_aws_route53_record.go#L661-L669) for some types of record such as [Weighted, Latency, Geo, and Failover resource records](https://github.com/datacratic/aws-sdk-go/blob/ac2c89bbe2f65afa1f5aaaf4f66ee105b43441d2/service/route53/api.go#L2758-L2760) to properly identifying record in the record set.
This PR adds it so Terraformer can properly import all type of Route 53 records.

Importing aws_route53_record loses some records due to missing SetIdentifier

---

providers/aws/s3.go

This change improved `terraformer import(plan) aws -r s3 -f aws_s3_bucket=bucketX` result.
* Import S3 bucket policy just related to only `aws_s3_bucket` (or `aws_s3_bucket_policy`) filter
Example
`terraformer import s3 -f "aws_s3_bucket=terraformer-test" `
We expect to import only `terraformer-test` bucket policy but current implementation import following bucket policies
* `bucket A`
* `bucket B`
* ...`bucket C..Z`
* `terraformer-test`
This change improved this behavior to import only `terraformer-test` bucket policy.

fix filtering of "import aws"

---

terraform_utils/resource.go

Currently, the `ConvertTFstate` is deleting keys of type arrays which are empty, without checking the `allowEmptyValues` argument.
This commit is intended to fix that.
https://github.com/GoogleCloudPlatform/terraformer/issues/137

Allow empty array

---

README.md
providers/aws/aws_provider.go
providers/aws/firehose.go

Hello.
This change support "aws_kinesis_firehose_delivery_stream" like following command.
```
terraformer import aws  -r firehose --regions "ap-northeast-1"
```
FYI
https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html
https://aws.amazon.com/kinesis/data-firehose/
Thank you.

aws: support firehose

---

README.md
cmd/cloudflare.go
cmd/root.go
providers/cloudflare/cloudflare_provider.go
providers/cloudflare/cloudflare_service.go
providers/cloudflare/dns.go
providers/cloudflare/firewall.go

This PR adds support [Cloudflare provider](https://www.terraform.io/docs/providers/cloudflare/index.html). Currently this provider supports the following resources:
* `firewall`
* `cloudflare_access_rule`
* `cloudflare_filter`
* `cloudflare_firewall_rule`
* `cloudflare_zone_lockdown`
* `dns`
* `cloudflare_zone`
* `cloudflare_record`

Support Cloudflare provider

---

providers/aws/firehose.go

I found `terraformer import aws -r firehose` failed in specific case (using S3 bucket as destination).
This code fix that bug.
`aws_kinesis_firehose_delivery_stream` can have either  `extended_s3_configuration` or `s3_configuration` attribute but this bug is not follow this constraint.
https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html
bug sample (`import-test` has both of `extended_s3_configuration` and `s3_configuration` in following case)
```
% terraform plan
Error: "extended_s3_configuration": conflicts with s3_configuration
on kinesis_firehose_delivery_stream.tf line 1, in resource "aws_kinesis_firehose_delivery_stream" "import-test":
1: resource "aws_kinesis_firehose_delivery_stream" "import-test" {
```

aws: Fix firehose import bug

---

go.mod
go.sum
providers/datadog/dashboard.go
providers/datadog/datadog_provider.go

Added support for new dashboard resource: https://www.terraform.io/docs/providers/datadog/r/dashboard.html
`> client.GetBoards()` is not in the **v2.21.0** release, so this is in draft mode for now. Will update go.mod after **v2.22.0** is out.
https://github.com/zorkian/go-datadog-api/releases

Add support for the new dashboard API

---

README.md
providers/aws/aws_provider.go
providers/aws/route_table.go

This PR adds support for importing AWS Route Table ([`aws_route_table`](https://www.terraform.io/docs/providers/aws/r/route_table.html)).

Add AWS Route Table Importing Option

---

go.mod
go.sum
providers/datadog/datadog_provider.go

The 0.7.9 build only takes api & app keys as environment variables, it does not respect the `--api-key` or `--app-key` flag. An `import` operation errors with:
```
2019/09/24 13:34:07 plugin error 1: Invalid or missing credentials provided to the Datadog Provider. Please confirm your API and APP keys are valid and see https://terraform.io/docs/providers/datadog/index.html for more information on providing credentials for the Datadog Provider
```

adjust setting datadog api & app key. Update zorkain/go-datadog-api library

---

providers/aws/iam.go

The `aws_iam_group_membership` resource must have `users` field even if this field has an empty element.
So I added `users` to `AllowEmptyValues`.
See Also: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_iam_group_membership.go#L28

fix: add missing required field in aws_iam_group_membership

---

terraform_utils/hcl.go

Route53 records `example.com` and `*.example.com` must have different identifiers, otherwise it will result:
```
[ERR]: duplicate resource found: aws_route53_record.ZZZZZZZZZZZZZZ_example.com_A_
```
This is fixed by removing `"*."` to `""` replace rule and then adding `"*"` to `"--"` replace rule. While `"."` will be handled by the `"."` to `"--"` existent rule.
The problem is described on Issue #169.

Fix Issue #169

---

README.md

To get terraformer to work with the AWS profiles I have in my `~/.aws/config` file, I had to set the `AWS_SDK_LOAD_CONFIG` to `true`.
Without that option, I get the following warning (with a ~25s delay) and nothing is imported:
```
Terraformer v0.8.0
2019/09/27 17:00:01 aws importing region eu-west-1
2019/09/27 17:00:01 aws importing... route53
2019/09/27 17:00:25 NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2019/09/27 17:00:25 [TRACE] GRPCProvider: GetSchema
2019/09/27 17:00:25 [TRACE] GRPCProvider: Configure
2019/09/27 17:00:38 [TRACE] GRPCProvider: GetSchema
2019/09/27 17:00:38 [TRACE] GRPCProvider: GetSchema
2019/09/27 17:00:38 [TRACE] GRPCProvider: Configure
2019/09/27 17:00:50 aws Connecting.... …
```

Document AWS_SDK_LOAD_CONFIG to load profiles from the shared config

---

README.md

Add the new `Datadog dashboard service` in the readme. 
Dashboard endpoint in Datadog API unifies screenboard and timeboard APIs.

fix: add Datadog dashboard service in the readme

---

providers/aws/cloudtrail.go
providers/aws/firehose.go

Removed sess inputs to some `createResources` functions since the input argument is never used.

Removed unused sess arguments

---

README.md
cmd/heroku.go
cmd/root.go
go.mod
go.sum
providers/heroku/addon.go
providers/heroku/app.go
providers/heroku/heroku_provider.go
providers/heroku/heroku_service.go

Adds support for the [Heroku provider](https://www.terraform.io/docs/providers/heroku/index.html). Also adds the following resources:
- [`heroku_app`](https://www.terraform.io/docs/providers/heroku/r/app.html)
- [`heroku_addon`](https://www.terraform.io/docs/providers/heroku/r/addon.html)

Support Heroku provider

---

README.md
providers/aws/aws_provider.go
providers/aws/eip.go

This PR adds support for importing [`aws_eip` resource](https://www.terraform.io/docs/providers/aws/r/eip.html) which corresponds to [Elastic IP](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html) allocation on AWS.

Add AWS Elastic IP

---

README.md
providers/aws/aws_provider.go
providers/aws/nat_gateway.go

This PR adds support for importing [`aws_nat_gateway` resource](https://www.terraform.io/docs/providers/aws/r/nat_gateway.html) which corresponds to [NAT Gateway](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html) instance on AWS.

Add AWS NAT Gateway

---

README.md
providers/aws/aws_provider.go
providers/aws/vpc_peering.go

This PR adds support for importing [`aws_vpc_peering_connection ` resource](https://www.terraform.io/docs/providers/aws/r/vpc_peering.html) which corresponds to [VPC Peering](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-peering.html) connection on AWS.

Add AWS VPC Peering Connection

---

README.md
cmd/aws.go

We should import global resources only once, without bounding with a specific region, as described in AWS docs (https://docs.amazonaws.cn/en_us/general/latest/gr/rande.html):
_Some services, such as IAM, do not support Regions. Thus, the endpoints for those services do not include a Region._
Ref #211

import AWS global resources only once

---

README.md
providers/heroku/account_feature.go
providers/heroku/addon_attachment.go
providers/heroku/app_config_association.go
providers/heroku/app_feature.go
providers/heroku/app_webhook.go
providers/heroku/build.go
providers/heroku/domain.go
providers/heroku/drain.go
providers/heroku/formation.go
providers/heroku/heroku_provider.go
providers/heroku/pipeline.go
providers/heroku/pipeline_coupling.go
providers/heroku/team_collaborator.go
providers/heroku/team_member.go

Adds support for a majority of Heroku resources. List of resources added:
* `heroku_account_feature`
* `heroku_addon_attachment`
* `heroku_app_config_association`
* `heroku_app_feature`
* `heroku_app_webhook`
* `heroku_build`
* `heroku_domain`
* `heroku_drain`
* `heroku_formation`
* `heroku_pipeline`
* `heroku_pipeline_coupling`
* `heroku_team_collaborator`
* `heroku_team_member`

Add support for Heroku resources

---

README.md
cmd/import.go
providers/aws/ebs.go
providers/aws/ec2.go
providers/aws/s3.go
terraform_utils/resource.go
terraform_utils/service.go
terraform_utils/service_test.go
terraform_utils/utils.go

Things done:
- It's possible to apply filters on all fields e.g. tags (ref #196 )
- Calls to fetch AWS EC2 and EBS resources take tag filters into account
- Filter values can contain `:` (ref #152 ) if value is wrapped in apostrophes `'`

Allowed filtering by all fields

---

README.md
cmd/provider_cmd_digitalocean.go
cmd/root.go
go.mod
go.sum
providers/digitalocean/database_cluster.go
providers/digitalocean/digitalocean_provider.go
providers/digitalocean/digitalocean_service.go
providers/digitalocean/domain.go
providers/digitalocean/droplet.go
providers/digitalocean/firewall.go
providers/digitalocean/floating_ip.go
providers/digitalocean/kubernetes_cluster.go
providers/digitalocean/loadbalancer.go
providers/digitalocean/project.go
providers/digitalocean/token_source.go
providers/digitalocean/volume.go

Adds support for the [DigitalOcean provider](https://www.terraform.io/docs/providers/do/index.html). Also adds the following resources:
* `digitalocean_database_cluster`
* `digitalocean_domain`
* `digitalocean_droplet`
* `digitalocean_firewall`
* `digitalocean_floating_ip`
* `digitalocean_kubernetes_cluster`
* `digitalocean_loadbalancer`
* `digitalocean_project`
* `digitalocean_volume`

Support DigitalOcean provider 🦈

---

README.md
cmd/provider_cmd_linode.go
cmd/root.go
go.mod
go.sum
providers/linode/domain.go
providers/linode/image.go
providers/linode/instance.go
providers/linode/linode_provider.go
providers/linode/linode_service.go
providers/linode/nodebalancer.go
providers/linode/sshkey.go
providers/linode/token.go
providers/linode/volume.go

Adds support for the [Linode provider](https://www.terraform.io/docs/providers/linode/index.html). Also adds the following resources:
* `linode_domain`
* `linode_image`
* `linode_instance`
* `linode_nodebalancer`
* `linode_sshkey`
* `linode_token`
* `linode_volume`

Support Linode provider

---

providers/logzio/alert_notification_endpoints.go
providers/logzio/alerts.go
providers/logzio/logzio_provider.go

Terraform 0.12 is grabbing the values coming back for the provider logzio_terraform_provider but these aren't being matched in the terraformer provider for logzio.
Changing the looked up values in terraformer rather than the provide to avoid downstream breaking.
token -> api_token
baseURL -> base_url

Match the config arguments to those in the provider.

---

providers/github/github_provider.go

Removes the unused `githubProviderVersion` `const`.

remove unused githubProviderVersion

---

terraform_utils/hcl.go

Previously, characters that could not be used in Terraform identifiers were replaced by `--`. This behavior cloud lead to a resource name collision, for example `(example)` and `[example]` would generate `--example--`.
Instead of replacing those characters with a fixed string, we can escape those characters making any two different string generate a unique Terraform identifier.
As specified in Terraform's documentation, `-` character is a valid identifier character, although it is not recommended to be used and `_` should be used instead. So I used `-` as a scape character.
Everything that is not `_` and is not between `0` and `9`, `A` and `Z`, and `a` and `z` should be escaped, `-` included. To escape characters we could simply use the character's Unicode value, so even emojis could be …

Escape Terraform Unsafe Characters instead of Replacing with `--`

---

README.md
providers/aws/aws_provider.go
providers/aws/cloud9.go

Adds support for the [`aws_cloud9_environment_ec2`](https://www.terraform.io/docs/providers/aws/r/cloud9_environment_ec2.html) resource.

Add support for AWS Cloud9

---

README.md
cmd/provider_cmd_rabbitmq.go
cmd/root.go
providers/rabbitmq/binding.go
providers/rabbitmq/exchange.go
providers/rabbitmq/helpers.go
providers/rabbitmq/permissions.go
providers/rabbitmq/policy.go
providers/rabbitmq/queue.go
providers/rabbitmq/rabbitmq_provider.go
providers/rabbitmq/rabbitmq_service.go
providers/rabbitmq/user.go
providers/rabbitmq/vhost.go
tests/rabbitmq/main.go

This PR will add the Terraformer provider for the Terraform RabbitMQ provider.

Add RabbitMQ provider

---

providers/rabbitmq/rabbitmq_provider.go

This PR will fix a typo (copy/paste ?) in providers/rabbitmq/rabbitmq_provider.go. Sorry !

Fix typo in rabbitmq_provider

---

providers/aws/aws_provider.go
providers/aws/route_table.go
terraform_utils/hcl.go

This PR adds `aws_route_table_association` and `aws_main_route_table_association` importing support along with `aws_route_table`.

Add aws_route_table_association importing support

---

go.mod
go.sum
providers/digitalocean/project.go

There was a bug in the DigitalOcean Go SDK where you were unable to use `IsLastPage()` to determine the last page for Projects so I originally used a workaround, but that has been fixed in  `v1.24.1` so I updated the `godo` version and refactored the Projects code to use `IsLastPage()`.

Update DigitalOcean Projects Pagination

---

README.md
cmd/provider_cmd_vultr.go
cmd/root.go
go.mod
go.sum
providers/vultr/bare_metal_server.go
providers/vultr/block_storage.go
providers/vultr/dns_domain.go
providers/vultr/firewall_group.go
providers/vultr/network.go
providers/vultr/reserved_ip.go
providers/vultr/server.go
providers/vultr/snapshot.go
providers/vultr/ssh_key.go
providers/vultr/startup_script.go
providers/vultr/user.go
providers/vultr/vultr_provider.go
providers/vultr/vultr_service.go

Adds support for the [Vultr provider](https://www.terraform.io/docs/providers/vultr/index.html). Also adds the following resources:
* `vultr_bare_metal_server`
* `vultr_block_storage`
* `vultr_dns_domain`
* `vultr_firewall_group`
* `vultr_network`
* `vultr_reserved_ip`
* `vultr_server`
* `vultr_snapshot`
* `vultr_ssh_key`
* `vultr_startup_script`
* `vultr_user`

Support Vultr provider 🐦 

---

README.md
cmd/import.go
cmd/provider_cmd_alicloud.go
cmd/provider_cmd_aws.go
cmd/provider_cmd_azure.go
cmd/provider_cmd_cloudflare.go
cmd/provider_cmd_datadog.go
cmd/provider_cmd_digitalocean.go
cmd/provider_cmd_github.go
cmd/provider_cmd_google.go
cmd/provider_cmd_heroku.go
cmd/provider_cmd_kubernetes.go
cmd/provider_cmd_linode.go
cmd/provider_cmd_logzio.go
cmd/provider_cmd_newrelic.go
cmd/provider_cmd_openstack.go
terraform_utils/connect.go
terraform_utils/connect_test.go
terraform_utils/service_test.go
terraform_utils/terraform_output/hcl.go
tests/aws/main.go

This PR simplifies the output resource structure. It's possible to:
1. Provide output path without `{service}` part, so that all resources will be saved in one directory
2. Provide `--compact` option which allows for saving all of providers resources under `resources.tf` file
If a user invokes terraformer with parameters `--path-pattern={output}/{provider}/ --compact=true`, all generated resources will be saved in `resources.tf` file in a provider's output directory.
This PR partially solves #242  - at least just one backend configuration to add.
It also organizes arguments across providers.

Allowed for more compacted options with output resources

---

README.md

I found some of AWS resource is already implemented, but not documented.
So I add aws resource name into README.md

add already implemented AWS resource type into README.

---

providers/alicloud/sg.go

Adds small check for the case of an error returned by the `initSecurityGroupRules` call in the Alicloud provider.

Handle Alicloud initSecurityGroupRules err

---

README.md
providers/heroku/cert.go
providers/heroku/heroku_provider.go

Adds support for the [`heroku_cert`](https://www.terraform.io/docs/providers/heroku/r/cert.html) resource.

Add support for Heroku Cert

---

README.md
providers/vultr/dns_domain.go

Adds support for the [`vultr_dns_record`](https://www.terraform.io/docs/providers/vultr/r/dns_record.html) resource.

Add support for Vultr DNS record

---

README.md
cmd/provider_cmd_fastly.go
cmd/root.go
go.mod
go.sum
providers/fastly/fastly_provider.go
providers/fastly/fastly_service.go
providers/fastly/service_v1.go

Fixes: #309 
Adds support for the [Fastly provider](https://www.terraform.io/docs/providers/fastly/index.html). Also adds the following resources:
* `fastly_service_acl_entries_v1`
* `fastly_service_dictionary_items_v1`
* `fastly_service_dynamic_snippet_content_v1`
* `fastly_service_v1`

Support Fastly provider ⏰

---

README.md
providers/digitalocean/domain.go

Adds support for the [`digitalocean_record`](https://www.terraform.io/docs/providers/do/r/record.html) resource.

Add support for DigitalOcean record

---

README.md
providers/digitalocean/kubernetes_cluster.go

Adds support for the [`digitalocean_kubernetes_node_pool`](https://www.terraform.io/docs/providers/do/r/kubernetes_node_pool.html) resource.

Add support for DigitalOcean Kubernetes node pool

---

README.md
providers/digitalocean/database_cluster.go

Adds support for the following resources: 
* [`digitalocean_database_db`](https://www.terraform.io/docs/providers/do/r/database_db.html)
* [`digitalocean_database_replica`](https://www.terraform.io/docs/providers/do/r/database_replica.html)
* [`digitalocean_database_user`](https://www.terraform.io/docs/providers/do/r/database_user.html)

Add support for DigitalOcean database resources

---

README.md
go.sum
providers/azure/analysis.go
providers/azure/azure_provider.go
providers/azure/database.go
providers/azure/helper.go

This PR add more resources into Azure provider
Fix #333 
*   `analysis`
* `azurerm_analysis_services_server`
*   `database`
* `azurerm_mariadb_configuration`
* `azurerm_mariadb_database`
* `azurerm_mariadb_firewall_rule`
* `azurerm_mariadb_server`
* `azurerm_mariadb_virtual_network_rule`
* `azurerm_mysql_configuration`
* `azurerm_mysql_database`
* `azurerm_mysql_firewall_rule`
* `azurerm_mysql_server`
* `azurerm_mysql_virtual_network_rule`
* `azurerm_postgresql_configuration`
* `azurerm_postgresql_database`
* `azurerm_postgresql_firewall_rule`
* `azurerm_postgresql_server`
* `azurerm_postgresql_virtual_network_rule`
* `azurerm_sql_database`
* `azurerm_sql_active_directory_administrator`
* `azurerm_sql_elasticpool`
* `azurerm_sql_failover_group`
* `azurerm_sql_firewall_rule`
* …

Add Azure Analysis & Databases

---

providers/azure/database.go

Makes sure each individual `err` returned from function calls within the `InitResouces()` function for Azure databases is checked.

handle errs in azure databases init resources

---

README.md
providers/cloudflare/cloudflare_service.go

In addition to email/API key, Cloudflare supports using actual API tokens with fine grained permissions: https://blog.cloudflare.com/api-tokens-general-availability/
This PR adds support for those.

Add support for Cloudflare API Token

---

README.md
providers/aws/accessanalyzer.go
providers/aws/aws_provider.go

Adds support for the [aws_accessanalyzer_analyzer](https://www.terraform.io/docs/providers/aws/r/accessanalyzer_analyzer.html) resource.

add support for aws_accessanalyzer_analyzer

---

README.md
providers/aws/aws_provider.go
providers/aws/codecommit.go

Adds support for the [aws_codecommit_repository](https://www.terraform.io/docs/providers/aws/r/codecommit_repository.html) resource.

add support for aws_codecommit_repository

---

providers/gcp/iam.go

This implements `google_project_iam_member` and `google_project_iam_custom_role` from #108 
It also adds a regex-check to the existing `google_service_account` import. When importing "google-managed" service accounts (which start with a number), subsequent `terraform plan`s would fail because "user-managed" service accounts cannot start with a number.
I've chosen for `_member` instead of `_policy`/`_binding` because having authoritative permissions on the project level, in combination with filtering, makes it very easy to break your IAM permissions by accident. 
Maybe it would be nice to have a GCP specific flag to be able to specify the type of IAM import you want? For now I've decided to keep this PR straightforward.

GCP: Project IAM Resources

---

README.md

Since there are two "\~"s consecutively in the readme, it leads to an unwanted strikethrough. added escapes to avoid this.

remove unwanted strikethrough in readme

---

README.md
providers/github/github_provider.go
providers/github/user_ssh_keys.go
providers/github/users.go

Adds support for the [`github_user_ssh_key`](https://www.terraform.io/docs/providers/github/r/user_ssh_key.html) resource.

Add support for github_user_ssh_key

---

README.md
providers/github/github_provider.go
providers/github/organization_block.go

Adds support for the [`github_organization_block`](https://www.terraform.io/docs/providers/github/r/organization_block.html) resource.

add support for github_organization_block

---

README.md
providers/github/github_provider.go
providers/github/organization_project.go

Adds support for the [`github_organization_project`](https://www.terraform.io/docs/providers/github/r/organization_project.html) resource.

add support for github_organization_project

---

README.md
providers/github/github_provider.go

Renames the resource options that I added to the GitHub provider to be plural so they align with the rest of the existing supported GitHub options.

refactor github resources to be plural

---

providers/aws/route53.go

Removing trailing dot in record names since Terraform requires a domain name without a trailing dot.
It is required to provide a set identifier for an AWS Route 53 Record in order for Terraform to import a correct record. The TF might have not ideal logic (see e.g. terraform-providers/terraform-provider-aws#11677) but the Terraformer logic is correct.
closes #118

Fixed Route 53 record name

---

README.md
providers/aws/aws_provider.go
providers/aws/codepipeline.go

Adds support for the [`aws_codepipeline`](https://www.terraform.io/docs/providers/aws/r/codepipeline.html) resource.

add support for aws_codepipeline

---

README.md
providers/aws/codepipeline.go

Adds support for the [`aws_codepipeline_webhook`](https://www.terraform.io/docs/providers/aws/r/codepipeline_webhook.html) resource.

add support for aws_codepipeline_webhook

---

go.mod
go.sum
vendor/github.com/zclconf/go-cty/cty/marks.go
vendor/modules.txt

In December a version of `go-cty` in version `1.2.0` was added to the project with a bug that causes stack overflows when decoding responses from plugins.
This issue was solved in zclconf/go-cty#35 and this PR updates the library to version `1.2.1` with the fix.
closes #374

 Updated go-cty library

---

terraform_utils/terraform_output/bucket.go

Currently:
```
terraform {
backend "gcs" {
bucket = "gs://<BUCKET_NAME>"
prefix = "."
}
}
```
Desired:
```
terraform {
backend "gcs" {
bucket = "<BUCKET_NAME>"
prefix = "."
}
}
```

FIX: config output must not contain `gs://` prefix

---

cmd/import.go

The generated variables.tf currently looks like:
```
data "terraform_remote_state" "local" {
backend = "gcs"
config = {
bucket = "gs://blah-tf-state"
prefix = "."
}
}
```
This change corrects the "bucket" field to:
```
data "terraform_remote_state" "local" {
backend = "gcs"
config = {
bucket = "blah-tf-state"
prefix = "."
}
}
```
Without this change, terraform complains that it cannot find
this resource.
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
data.terraform_remote_state.local: Refreshing state...
Error: Error loading state error
on variables.tf line 2, in data "terraform_remote_state" "local":
2:   backend = "gcs"
error loading the remote …
```

Correct bucket reference in generated  variables.tf

---

README.md
providers/aws/aws_provider.go
providers/aws/datapipeline.go

Adds support for the [`aws_datapipeline_pipeline`](https://www.terraform.io/docs/providers/aws/r/datapipeline_pipeline.html) resource.

add support for aws_datapipeline_pipeline

---

README.md
providers/aws/aws_provider.go
providers/aws/devicefarm.go

Adds support for the [`aws_devicefarm_project`](https://www.terraform.io/docs/providers/aws/r/devicefarm_project.html) resource.

add support for aws_devicefarm_project

---

README.md
providers/aws/aws_provider.go
providers/aws/media_package.go

Adds support for the [`aws_media_package_channel`](https://www.terraform.io/docs/providers/aws/r/media_package_channel.html) resource.

add support for aws_media_package_channel

---

providers/aws/aws_service.go
providers/aws/cloudformation.go
providers/aws/iam.go
providers/aws/s3.go

IAM policies can contain variables [1] that can break TF format, as same as CF templates, so they must be escaped.
[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html

Escape AWS interpolation in IAM + S3 Policies

---

README.md
providers/aws/aws_provider.go
providers/aws/media_store.go

Adds support for the [`aws_media_store_container`](https://www.terraform.io/docs/providers/aws/r/media_store_container.html) resource.

add support for aws_media_store_container

---

providers/aws/igw.go

TF can manage only IGWs attached to a VPC.
closes #430

Import only attached internet gateways

---

go.mod
go.sum

```
$ terraformer version
Terraformer v0.8.6
$ terraformer import  fastly -r service_v1
...
goroutine 1092 [chan receive]:
github.com/GoogleCloudPlatform/terraformer/terraform_utils.RefreshResourceWorker(0xc0001926c0, 0xc00072cb90, 0xc0004a25a0)
/private/tmp/terraformer-20200207-19342-s2q293/src/github.com/GoogleCloudPlatform/terraformer/terraform_utils/utils.go:107 +0xf6
created by github.com/GoogleCloudPlatform/terraformer/terraform_utils.RefreshResources
/private/tmp/terraformer-20200207-19342-s2q293/src/github.com/GoogleCloudPlatform/terraformer/terraform_utils/utils.go:79 +0x103
goroutine 1093 [chan receive]:
github.com/GoogleCloudPlatform/terraformer/terraform_utils.RefreshResourceWorker(0xc0001926c0, 0xc00072cb90, 0xc0004a25a0) …
```

Fix fastly import issue

---

README.md
go.sum
providers/aws/appsync.go
providers/aws/aws_provider.go
vendor/modules.txt

```
❯ terraform output
aws_appsync_graphql_api_tfer--AppSyncTest_id = dpwxm4lkvjg2rmvvfcvz7g3gku
```
AppSyncTest being api name here
There are other sub-resources related to this service (https://www.terraform.io/docs/providers/aws/r/appsync_graphql_api.html)
they can be added later too

Add preliminary import support for aws_appsync_graphql_api

---

README.md
providers/aws/aws_provider.go
providers/aws/xray.go
vendor/modules.txt

```
❯ ./terraformer import aws --resources xray --regions ap-southeast-1                                                  
2020/03/30 19:31:36 aws importing region ap-southeast-1
2020/03/30 19:31:36 aws importing... xray                                         
2020/03/30 19:31:40 Refreshing state... aws_xray_sampling_rule.tfer--testRule                
2020/03/30 19:31:40 Refreshing state... aws_xray_sampling_rule.tfer--Default
2020/03/30 19:31:40 aws Connecting....                                                                     
2020/03/30 19:31:40 aws save xray     
2020/03/30 19:31:40 aws save tfstate for xray           
```

Add import support for aws_xray_sampling_rule

---

README.md
providers/aws/aws_provider.go
providers/aws/cognito.go
vendor/modules.txt

```
❯ ./terraformer import aws --resources cognito --regions ap-southeast-1
2020/03/27 13:53:05 aws importing region ap-southeast-1
2020/03/27 13:53:05 aws importing... cognito
2020/03/27 13:53:05 aws importing cognito_identity_pool: ap-southeast-1:9e3f8239-0c8a-43ab-ac5c-c936b14649d2
2020/03/27 13:53:05 aws importing cognito_user_pool: ap-southeast-1_bZWf5VS8d
2020/03/27 13:53:10 Refreshing state... aws_cognito_identity_pool.tfer--test_cognitoidentity
2020/03/27 13:53:10 Refreshing state... aws_cognito_user_pool.tfer--testUserPool
2020/03/27 13:53:11 aws Connecting.... 
2020/03/27 13:53:11 aws save cognito
2020/03/27 13:53:11 aws save tfstate for cognito
```
Support of `aws_cognito_user_pool_client` is not straightforward (What to fill to the call parameter for CreateResource for `id` so …

Add preliminary import support for aws_cognito_userpool/aws_cognito_identity_pool

---

README.md
cmd/provider_cmd_keycloak.go
go.mod
go.sum
providers/keycloak/generator.go
providers/keycloak/group.go
providers/keycloak/keycloak_provider.go
providers/keycloak/openid_client.go
providers/keycloak/realm.go
providers/keycloak/role.go
providers/keycloak/scope.go
providers/keycloak/user.go
vendor/modules.txt

Hi,
Here is a new version of my provider. I changed a lot of things.
I removed terraformer resources and kept only `realms` elsewhere I have to much loop dependencies when I use the terraform generated code to initialize an empty keycloak instance.
I support new resources, but not all the resources supported by the terraform provider.
Regards,
Pierre

feat: keycloak v2, consolidate all under realms, add new mappers

---

cmd/plan.go

Currently the plan file is opened for writing without being truncated, so if used for multiple consecutive runs the new plan can end up only partially overwriting the old one, resulting in invalid json.
Adding `O_TRUNC` to the `OpenFile` flags resolves this.
Tested using AWS provider on Windows.

Truncate the plan file before writing to prevent invalid JSON

---

providers/commercetools/shipping_zone.go

The shipping_zone [key is optional in Commercetools](https://docs.commercetools.com/http-api-projects-zones#zone), this PR change the logic to use the name field instead when the key is not defined.
close https://github.com/GoogleCloudPlatform/terraformer/issues/479

Fix undefined key in Commercetools shipping_zone 

---

README.md
go.mod
go.sum
providers/commercetools/commercetools_provider.go
providers/commercetools/shipping_method.go

- Commercetools provider to support `shipping_method` resource
- upgrade `github.com/labd/commercetools-go-sdk` to latest, make i
- update vendor directory: not sure how to deal with this directory, I committed the changes made after running the `go mod vendor` command. I would personaly remove it from this repository but I guess that's a different problem.
close https://github.com/GoogleCloudPlatform/terraformer/issues/478

Add shipping_method resource to Commercetools provider

---

providers/azure/virtual_machine.go

Hey guys!
Cool tool!
I was testing it out, and noticed it was creating `azurerm_virtual_machine` ([here](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html)) for all of my instances. However:
So I added an `if` that handles this case.

Replace the deprecated azurerm_virtual_machine

---

cmd/import.go

I noticed that the error of `provider.GetService().InitResources()` doesn't be handled currently.
Because of that, terraformer continues the import process even if the provider returns an error.

Fix missing error handling when importing resources

---

README.md

PR #354 added support for Google Project IAM resources, but did not update the README (as mentioned in #108. This PR fixes that.

Add Google IAM to README.md

---

README.md
providers/aws/aws_provider.go
providers/aws/servicecatalog.go

Adds support for the [`aws_servicecatalog_portfolio`](https://www.terraform.io/docs/providers/aws/r/servicecatalog_portfolio.html) resource.

add support for aws_servicecatalog_portfolio

---

README.md
providers/aws/iam.go
terraformutils/providerwrapper/provider.go

Improved resource import. In some cases Terraform is unable to perform resource refresh and the only option that is left is a regular resource import. That import will not import attributes into TF file but should be sufficient for resources with small number of attributes e.g. `aws_iam_role_policy_attachment `.
The fix might solve other resources that return error _Read resource response is null for resource ..._ e.g. #482 #489 #473 and others
fixes #467

Improved resource import

---

providers/azure/database.go

(cherry picked from commit c74d01e53f3c57e0a0a7a4638d130a9f500a55ce)
We run 2 SQL servers, and ran into an issue where the `master` database existed in both servers. This happens in Posgres as well.
This solves this by adding the server name to the relevant resource

Handle uniqueness of DBs and configurations

---

go.mod
go.sum

Here is what I did:
- bump tf version to 0.12.27
- `go mod tidy` the deps with go 1.14.4

chore(deps): bump terraform to v0.12.27

---

README.md
providers/azure/azure_provider.go
providers/azure/cosmosdb.go

- There are minor workarounds,please refer to the `NOTE:` blocks 
[azure resource id renaming & function interface changing across versions ]
```
╰─ ./terraformer import  azure --resources cosmosdb                                                                                                        ─╯
2020/07/05 19:52:29 Testing if Service Principal / Client Certificate is applicable for Authentication..
2020/07/05 19:52:29 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2020/07/05 19:52:29 Testing if Service Principal / Client Secret is applicable for Authentication..
2020/07/05 19:52:29 Testing if Managed Service Identity is applicable for Authentication..
2020/07/05 19:52:29 Testing if Obtaining a token from the Azure CLI is applicable for …
```

Add partial cosmosdb resources support (Azure Table / SQL) for azurerm provider 

---

README.md
providers/azure/azure_provider.go
providers/azure/load_balancer.go

```
❯ terraform refresh
azurerm_lb_nat_rule.tfer--testInboundNATrule: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/loadBalancers/testLoadBalancer/inboundNatRules/testInboundNATrule]
azurerm_lb_backend_address_pool.tfer--testBackendPool: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/loadBalancers/testLoadBalancer/backendAddressPools/testBackendPool]
azurerm_lb_probe.tfer--testProbe1: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/loadBalancers/testLoadBalancer/probes/testProbe1]
azurerm_lb.tfer--testLoadBalancer: Refreshing state... …
```

Add partial azurerm_lb_* support

---

README.md
providers/azure/azure_provider.go
providers/azure/container.go

```
azurerm_container_registry.tfer--testContainerRegistryLLLL: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.ContainerRegistry/registries/testContainerRegistryLLLL]
azurerm_container_registry_webhook.tfer--testWebhook: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.ContainerRegistry/registries/testContainerRegistryLLLL/webhooks/testWebhook]
azurerm_container_group.tfer--test-002D-container-002D-jjjjj: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.ContainerInstance/containerGroups/test-container-jjjjj]
Outputs:
azurerm_container_group_tfer--test-002D-container-002D-jjjjj_id = …
```

Add preliminary support for  azurerm_container_*

---

README.md
providers/azure/azure_provider.go
providers/azure/private_dns.go

```
azurerm_private_dns_txt_record.tfer--testtxt: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/privateDnsZones/testprivatedns.dns/TXT/testtxt]
azurerm_private_dns_mx_record.tfer--testmx: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/privateDnsZones/testprivatedns.dns/MX/testmx]
azurerm_private_dns_a_record.tfer--testa: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/privateDnsZones/testprivatedns.dns/A/testa]
azurerm_private_dns_ptr_record.tfer--testptr: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Micros …
```

Add azurerm_private_dns_* support

---

README.md
providers/azure/azure_provider.go
providers/azure/public_ip.go

```
azurerm_public_ip_prefix.tfer--testPublicIPPrefixInsance: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/publicIPPrefixes/testPublicIPPrefixInsance]
azurerm_public_ip.tfer--testPublicAddress: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/publicIPAddresses/testPublicAddress]
Outputs:
azurerm_public_ip_prefix_tfer--testPublicIPPrefixInsance_id = /subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/publicIPPrefixes/testPublicIPPrefixInsance
azurerm_public_ip_tfer--testPublicAddress_id = /subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/publicIPA …
```

Add azurerm_public_ip* support

---

README.md
cmd/provider_cmd_yandex.go
cmd/root.go
go.mod
go.sum
providers/yandex/compute_disk.go
providers/yandex/compute_instance.go
providers/yandex/util.go
providers/yandex/vpc_network.go
providers/yandex/vpc_subnet.go
providers/yandex/yandex_provider.go
providers/yandex/yandex_service.go

For resource types:
* Compute Instance
* Compute Disk
* VPC Subnet
* VPC Network

Init Yandex Cloud support (terraform-provider-yandex)

---

README.md
cmd/provider_cmd_alicloud.go
cmd/provider_cmd_aws.go
cmd/provider_cmd_cloudflare.go
cmd/provider_cmd_commercetools.go
cmd/provider_cmd_datadog.go
cmd/provider_cmd_digitalocean.go
cmd/provider_cmd_fastly.go
cmd/provider_cmd_github.go
cmd/provider_cmd_gmailfilter.go
cmd/provider_cmd_google.go
cmd/provider_cmd_heroku.go
cmd/provider_cmd_keycloak.go
cmd/provider_cmd_kubernetes.go
cmd/provider_cmd_linode.go
cmd/provider_cmd_logzio.go
cmd/provider_cmd_mikrotik.go
cmd/provider_cmd_newrelic.go
cmd/provider_cmd_openstack.go
cmd/provider_cmd_rabbitmq.go
cmd/provider_cmd_vultr.go
providers/aws/api_gateway.go
providers/aws/autoscaling.go
providers/aws/ebs.go
providers/aws/ec2.go
providers/aws/s3.go
terraformutils/resource.go
terraformutils/service.go
terraformutils/service_test.go
terraformutils/tfstate_converter_test.go

Currently, `--resources` option uses service name (e.g.
`resource_group` for azure) (assuming this is because the provider
name has already appeared in the command, no need to repeat).
Whilst, `--filter` option uses resource name (e.g. `azurerm_resource_group`).
This inconsistency causes confusion and is easy to make mistake
(actually current README and helper message have those mistakes).
To make them consistent addresses this issue. This PR chooses to make
`--filter` to use the service name, following the convention as
`--resources`.

`--filter` use service name instead of resource name

---

terraformutils/resource.go
terraformutils/terraformoutput/hcl.go

When user specify `-C`, current code doesn't record the referenced
attributes in the output config.
This PR addresses that issue by adding an additional check on whether
we are in compact mode. If yes, then it means the `resources` under
iteration belongs to different services, and we will only record the
output for current resource when the connection's target service is
the same as this resource's service type.

Fix missing output variables when compact output

---

providers/aws/sns.go
providers/aws/sqs.go

if accepted this PR will format the `policy` field for `sqs` and `sns` resources in those that have this attribute configured

format policy for aws sqs and sns resources as heredoc

---

go.mod
go.sum
providers/datadog/dashboard.go

This adds the ability to filter Datadog dashboards by ID, and switch to
use the officially supported client.

Add filter support to datadog dashboards

---

providers/datadog/dashboard.go
providers/datadog/datadog_provider.go

This adds the official Datadog client and auth context to the DatadogProvider struct avoiding code duplication in resources when the official Datadog client is used.

Add Datadog API client to DatadogProvider struct

---

providers/datadog/monitor.go

This PR adds support for filtering datadog monitor by id and updates the api client to use the supported datadog go client.

Add filter support to datadog monitor

---

providers/datadog/downtime.go

This PR adds support for filtering datadog downtimes by id and updates the api client to use the supported datadog go client.

Add filter support to datadog downtime

---

providers/aws/aws_provider.go
providers/aws/ec2.go

When importing an AWS EC2 instance do not leave out the secondary EBS volumes that are attached to it.
This is different from importing an EBS volume and trying to figure out what is attached.

Import AWS EC2 instance volumes

---

README.md
cmd/provider_cmd_datadog.go
providers/datadog/datadog_provider.go

This PR adds support for passing custom Datadog api url allowing users from different regions such as EU to use the tool as well by setting the flag: `--api-url=https://api.datadoghq.eu` or env variable `DATADOG_HOST=https://api.datadoghq.eu`

Add support for passing Datadog api url

---

build/main.go
cmd/import.go
cmd/provider_cmd_github.go
cmd/provider_cmd_google.go
cmd/provider_cmd_keycloak.go
cmd/provider_cmd_yandex.go
providers/alicloud/connectivity/endpoint.go
providers/aws/autoscaling.go
providers/aws/iam.go
providers/datadog/user.go
providers/gcp/clouddns.go
providers/gcp/dataproc.go
providers/gcp/gcp_compute_code_generator/main.go
providers/gcp/gcp_compute_code_generator/resources.go
providers/gcp/gcs.go
providers/gcp/gke.go
providers/gcp/instances.go
providers/github/repositories.go
providers/gmailfilter/label.go
providers/keycloak/openid_client.go
providers/openstack/compute.go
terraformutils/hcl.go
terraformutils/json.go
terraformutils/terraformoutput/bucket.go
terraformutils/terraformoutput/hcl.go

Command: `golangci-lint run  --out-format=tab  ./...`
<details>
<summary>Issues reported</summary>
| File| REPORTER | DESCRIPTION |
| --- | ----- | ----- |
| providers/aws/autoscaling.go:65:42                          | gocritic |   commentFormatting: put a space between `//` and comment text |
| providers/aws/iam.go:186:19                                 | gocritic |   wrapperFunc: use strings.ReplaceAll method in `strings.Replace(resourceName, "@", "", -1)` |
| providers/gmailfilter/label.go:37:4                         | gocritic |   wrapperFunc: use strings.ReplaceAll method in `strings.Replace(l.Name, "/", "_", -1)` |
| cmd/import.go:226:41                                        | gocritic |   wrapperFunc: use strings.ReplaceAll method in `strings.Replace(path, serviceName, k, -1)` | …

Fix all golangci-lint errors

---

providers/datadog/monitor.go

Synthetics should be imported and modified using Synthetics resources. This PR will exclude monitors with type `synthetics alert` from being imported.

Exclude synthetics monitor from being imported

---

terraformutils/hcl.go
terraformutils/hcl_test.go

This tries to handle the case where a field has the same name under different subschemas in the same resource, one of them being a map. Currently, it replaces all occurrences to the map version, but we can properly detect where we are in the hierarchy.

Handle nested maps in terraform12Adjustments

---

tests/datadog/README.md
tests/datadog/helper.go
tests/datadog/main.go
tests/datadog/resources/dashboard.tf
tests/datadog/resources/downtime.tf
tests/datadog/resources/monitor.tf
tests/datadog/resources/outputs.tf
tests/datadog/resources/synthetics.tf
tests/datadog/resources/user.tf

This PR adds a script to automate testing creation and importing of resources from Datadog.

Datadog test script

---

providers/openstack/compute.go

When importing volume attachments from an instance, with
a name with special charaters such as a dot, and with multiple attachments,
the depends_on contained the literal dot.

Add missing terraformutils.TfSanitize

---

providers/alicloud/alicloud_provider.go

fixes https://github.com/GoogleCloudPlatform/terraformer/issues/681
`p.Service` is not initialized when we call `GetConfig` here:
https://github.com/GoogleCloudPlatform/terraformer/blob/master/cmd/import.go#L113-L116
and it's better to use `p.profile` field which is initialized in `Init()`:
https://github.com/GoogleCloudPlatform/terraformer/blob/b9a6ae6e7de30c81d62649ce4b47c657cb19986c/providers/alicloud/alicloud_provider.go#L112-L116
```
$ terraformer import alicloud --resources=* --profile=<xxx> --regions cn-hangzhou
2020/12/01 20:17:17 alicloud importing region cn-hangzhou
2020/12/01 20:17:17 Attempting an import of ALL resources in alicloud
2020/12/01 20:17:17 provider name: alicloud
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation …
```

providers/alicloud: shouldn't access p.Service in GetConfig()

---

README.md

Fix typo on README for the Azure `public_ip` section

Fix typo on Azure public IP section

---

providers/rabbitmq/rabbitmq_provider.go
providers/rabbitmq/shovel.go

Hey there! thank you for making terraformer opensource. This afternoon I tried to add shovel support for rabbitmq provider however I'm missing something. This pull request is almost completed except for that part.
```
+ ../terraformer import rabbitmq -v -p '{output}/{provider}/' --resources=shovels                                                                                                                                                                              
2020-12-27T21:56:04.769+0100 [INFO]  plugin: configuring client automatic mTLS                                                                                                                                                                                 
2020-12-27T21:56:04.798+0100 [DEBUG] plugin: starting plugin: …
```

add support for rabbitmq shovels

---

README.md

This fixes a link that was accidentally copy and pasted

Fix mikrotik link to point to the correct provider

---

go.mod
go.sum
providers/datadog/datadog_provider.go

This PR bumps the datadog-api-go-client version and also introduces support for datadog v2 api.

Update datadog-api-go-client library version

---

README.md
providers/datadog/datadog_provider.go
providers/datadog/role.go

This PR adds support for the following Datadog resources:
- datadog_role
This PR is dependent on and needs https://github.com/GoogleCloudPlatform/terraformer/pull/752 to be merged first

Add support for datadog_role resource

---

README.md
providers/datadog/datadog_provider.go
providers/datadog/security_monitoring_default_rule.go
providers/datadog/security_monitoring_rule.go

This PR adds support for the following Datadog resources:
- datadog_security_monitoring_default_rule
- datadog_security_monitoring_rule

Add support for datadog security resources

---

terraformutils/providerwrapper/provider.go

This PR adds support for terraform v14 provider path format:
```
.terraform/providers/registry.terraform.io/<provider>/<provider>/<version>/<os>/
```

Support terraform v14 plugin path

---

terraformutils/providerwrapper/provider.go
terraformutils/providerwrapper/provider_test.go

This PR fixes regex generation for nested attributes. For example, in datadog dashboards the following is possible. The widget attribute has an `ID` field which is `computed`:
```
widget {
group_definition {
widget {
...
}
}
}
```
Resulting rule generations for the above were previously:
```
^group_definition.(.*).id$ 
^widget.[0-9].id($|\.[0-9]|\.#)
```
With the changes in this PR:
```
^widget.[0-9]+.group_definition.(.*).id$ 
^widget.[0-9]+.id($|\.[0-9]+|\.#)
```
-------------------------
The PR also ensures we properly handle nested attributes with `len(attributes) > 9`

Properly ignore nested attributes 

---

providers/gcp/gcp_provider.go

Print out errors when the wrong region selected otherwise some resources silently will not be generated.

Print out errors when wrong region selected

---

go.mod
go.sum
providers/mikrotik/mikrotik_provider.go
providers/mikrotik/mikrotik_service.go

While developing #846, I ran into an issue where adding the xenorchestra support was causing the following runtime crash.
```
ddelnano@ddelnano-desktop:~/code/terraformer$ ./terraformer
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag
goroutine 1 [running]:
encoding/gob.RegisterName(0x38e8e9d, 0x18, 0x3f5b100, 0x0)
/usr/lib/go/src/encoding/gob/type.go:820 +0x567
encoding/gob.Register(0x3f5b100, 0x0)
/usr/lib/go/src/encoding/gob/type.go:874 +0x12c
github.com/hashicorp/terraform-plugin-sdk/internal/tfdiags.init.0()
/home/ddelnano/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfdiags/rpc_friendly.go:58 +0x36
```
I tracked this down to the fact that terraformer has multiple …

Upgrade the mikrotik dependency to the new mikrotik client module and remove the transitive terraform-plugin-sdk dependency

---

terraformutils/providerwrapper/provider.go
terraformutils/terraformoutput/hcl.go

This PR includes 2 fixes:
1) Escape period (".") characters in the generated exclude regexes. 
2) Fix output values. Current behavior is the generated output is interpreted as a string rather than an interpolated value:
```
output "datadog_dashboard_tfer--dashboard_aat-002D-zsc-002D-rag_id" {
value = "datadog_dashboard.tfer--dashboard_aat-002D-zsc-002D-rag.id"
}
$ terraform apply
> Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
datadog_dashboard_tfer--dashboard_aat-002D-zsc-002D-rag_id = datadog_dashboard.tfer--dashboard_aat-002D-zsc-002D-rag.id
```

Escape period characters and fix output values

---

docs/datadog.md
providers/datadog/service_level_objective.go

It is now possible to list all SLO's for the datadog resource without having to manually specify an id. This PR removes the previous constraint set to require `id` to be passed.

Remove filter requirement for Datadog SLO resource

---

.github/workflows/release.yaml
README.md
cmd/provider_cmd_pagerduty.go
cmd/root.go
docs/pagerduty.md
go.mod
go.sum
providers/pagerduty/business_service.go
providers/pagerduty/escalation_policy.go
providers/pagerduty/pagerduty_provider.go
providers/pagerduty/pagerduty_service.go
providers/pagerduty/ruleset.go
providers/pagerduty/schedule.go
providers/pagerduty/service.go
providers/pagerduty/team.go
providers/pagerduty/user.go

This PR adds a provider for PagerDuty that is able to collect business_services, escalation_policy, ruleset, shcedule, service, team and users from the PagerDuty API.

Add PagerDuty Provider

---

cmd/provider_cmd_datadog.go
docs/datadog.md
providers/datadog/datadog_provider.go

This complies with the corresponding [schema arg](https://registry.terraform.io/providers/DataDog/datadog/latest/docs#schema). It is passed as a string and parsed to a bool and complies with the existing convention of giving priority to the arg before the env var DATADOG_VALIDATE. It defaults to true to comply with the provider schema behavior
I didn't run the tests because I wasn't sure about this warning:
```
The script will create and destroy real resources. Never run this on a production Datadog organization.
```
How should I test this so it's safe? I built it locally and It works for what I am trying to accomplish

Issue #911. Add a --validate arg for the datadog provider

---

providers/datadog/datadog_provider.go

I see my [previous PR](https://github.com/GoogleCloudPlatform/terraformer/pull/914) was already merged. I meant to get this one in too before it

Issue #911. Prevent throwing error for datadog api key or app key if validate=false, which is consistent with the provider behavior

---

docs/datadog.md
go.mod
go.sum
providers/datadog/dashboard.go
providers/datadog/dashboard_json.go
providers/datadog/dashboard_list.go
providers/datadog/datadog_provider.go
providers/datadog/downtime.go
providers/datadog/integration_aws.go
providers/datadog/integration_aws_lambda_arn.go
providers/datadog/integration_aws_log_collection.go
providers/datadog/integration_azure.go
providers/datadog/integration_gcp.go
providers/datadog/integration_slack_channel.go
providers/datadog/logs_archive.go
providers/datadog/logs_custom_pipeline.go
providers/datadog/logs_index.go
providers/datadog/logs_integration_pipeline.go
providers/datadog/monitor.go
providers/datadog/role.go
providers/datadog/security_monitoring_default_rule.go
providers/datadog/security_monitoring_rule.go
providers/datadog/service_level_objective.go
providers/datadog/synthetics.go
providers/datadog/synthetics_global_variable.go
providers/datadog/synthetics_private_location.go
providers/datadog/synthetics_test_.go
providers/datadog/user.go

This PR does several things:
- Updates the DD API Client to latest
- Renames synthetics -> synthetics_test to keep it on par with datadog terraform provider
- Adds new DashboardJSON resource
- Add support for filtering users by their `status`
- Allow setting empty `message` attribute for monitors
Thanks!

Update Datadog api client and various fixes

---

go.mod
go.sum

- terraform 0.12.31 is the latest 0.12.x release series.
- go mod cleanup the `go.sum` file

deps: upgrade terraform to v0.12.31

---

go.mod
go.sum
providers/aws/aws_provider.go
providers/aws/batch.go

Add support for import AWS Batch related objects, concretely:
- Batch compute environment
- Job definition
- Job queues
see more on Terraform [aws provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_compute_environment).
Tested against account in eu-central-1 with multiple compute environments, job definition (with different revisions) and job queues. Worked for me without issues.

Add support for AWS Batch

---

cmd/provider_cmd_panos.go
docs/panos.md
providers/panos/device_config.go
providers/panos/helpers.go
providers/panos/panos_provider.go
providers/panos/panos_service.go

- Improve authentication by letting [pango](https://github.com/PaloAltoNetworks/pango) managing the authentication
- Fix `panos_telemetry`, I was using the wrong ID
- Improve logging of [pango](https://github.com/PaloAltoNetworks/pango), now you can set PANGO_LOGGING to whatever you want (supported by pango); by default the log level is `quiet` (for other log levels, you can look at https://github.com/PaloAltoNetworks/pango/blob/05ba3593d486d205a4723bfce11c37994103ee8c/client.go#L1272-L1287)
- Update documentation

feat(panos): improve authentication, fix panos_telemetry

---

README.md
cmd/provider_cmd_vault.go
cmd/root.go
docs/vault.md
go.mod
go.sum
providers/vault/types.go
providers/vault/vault_provider.go
providers/vault/vault_service_generator.go

This commit includes the boilerplate for the Vault provider, as well
as support for Secret Engine, Secret Engine Roles, Auth Backends, Auth
Backend Roles, Auth Backend Users, Auth Backend Groups, and Policies. This is
done by instantiating a common Vault client using its official Go client
library and leveraging the naming convention of Vault tf resources to support
most of the Secret/Auth options available in the provider itself. The
provider configuration includes only the minimum required `address` and `token`
fields. Filtering roles/users/groups by mount type is supported as well as
basic filtering by resource ids.

Issue #962 add Hashicorp Vault provider partial support

---

providers/grafana/dashboard.go

This PR updates the Grafana provider to support Grafana versions >= 8.0.0.
Before Grafana 5.x, the only way to `GET` dashboards was by means of passing the dashboard slug name. With version 5.0.0, that changed to also include the ability to get by UID. Now, in version 8, the old route was deleted: https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-0-0/#breaking-changes.
This change will break the provider for users of Grafana < 5.0.0, but since that release has been out for three years, and this provider is fairly new to Terraformer, we don't think that this should be a concern for us.

Support Grafana 8

---

providers/vault/vault_provider.go
providers/vault/vault_service_generator.go

Follow up on Issue #964. Filtering by backend can be done using the regular filtering mechanism, so its unnecessary to have this filter here as well
Also adds [vault_mount](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/mount) resource

Remove filterAllow function when fetching Vault backend ids

---

providers/aws/firehose.go
providers/datadog/datadog_provider.go

Solves #976 
I solved the issue. 
There was a problem during retrieve of firehose streams when the number of streams in the region is over 10 (the default limit value of `ListDeliveryStreams` API). For further info read the documentation linked below.
https://docs.aws.amazon.com/firehose/latest/APIReference/API_ListDeliveryStreams.html#Firehose-ListDeliveryStreams-request-ExclusiveStartDeliveryStreamName
Unfortunately I couldn't write an unit test because of the code design. I wasn't able to write a firehose mock.
Any suggestion is welcome.

fixed #976

---

providers/vault/vault_service_generator.go

This policy cannot be updated or deleted and has no hcl associated so it does not seem proper to manage in Terraform generally

Prevent Vault root acl policy from being imported

---

terraformutils/providerwrapper/provider.go

This PR attempts to resolve: https://github.com/GoogleCloudPlatform/terraformer/issues/982
The widget schema that is currently ignored: https://github.com/DataDog/terraform-provider-datadog/blob/141501334a01ba32c14cc243d6df835087c70a76/datadog/resource_datadog_dashboard.go#L598
**Behavior**:
The above widget schema contains a single attribute `id`, which is `computed`, and many `NestedBlocks`. Hence when the `readObjBlocks` is called on the `widget` block, `if fieldCount == len(v.Block.Attributes) && fieldCount > 0` will compute to `True` and the regex `^widget` is added to the ignore list.
The logic behind this seems to be to ignore the entire block if all attributes within the block are computed. This PR adds an extra conditional to ensure that block is not ignored if it has nested …

Fix ignored blocks when all attributes are ignored although it includes nested blocks

---

providers/github/repositories.go

The display name was used for GitHub users instead of the login name, leading to errors while refreshing when they are different.
Fixes part of #990, where these issues were reported.

Fix GitHub repoitory_collaborator resource user login

---

cmd/provider_cmd_panos.go
docs/panos.md
go.mod
go.sum
providers/panos/firewall_device_config.go
providers/panos/firewall_networking.go
providers/panos/firewall_objects.go
providers/panos/firewall_policy.go
providers/panos/helpers.go
providers/panos/panorama_device_config.go
providers/panos/panorama_networking.go
providers/panos/panorama_objects.go
providers/panos/panorama_plugins.go
providers/panos/panorama_policy.go
providers/panos/panos_provider.go
providers/panos/panos_service.go

Add Panorama support to the PAN-OS provider.
To get the support of `panos_panorama_security_rule_group`, I had to do something really tricky (https://github.com/Trois-Six/terraformer/blob/feat/add-panorama-to-panos/providers/panos/panorama_policy.go#L122-L124), due to https://github.com/PaloAltoNetworks/terraform-provider-panos/blob/master/panos/resource_panorama_security_rule_group.go#L401-L403... but it works!

feat(panos): add PAN-OS Panorama support

---

providers/datadog/dashboard.go

`Query` is a required field in the `manage_status_definition`. This PR add this attribute to the AllowEmptyValues list

Fix dashboard widget generation

---

providers/pagerduty/pagerduty_provider.go

**Problem**
Although [Docs](https://github.com/GoogleCloudPlatform/terraformer/blob/e31a0f68a8fc8be9385d0c615d924bd95bd50b2d/docs/pagerduty.md) say `PAGERDUTY_TOKEN` in env is available, terraformer ignored the token when I tried the below:
```
$ export PAGERDUTY_TOKEN=hogehoge
$ terraformer import pagerduty -r user
```
**Cause**
`args[0]==TOKEN` if I specify `-t TOKEN` otherwise `args[0]==""`.
When `PAGERDUTY_TOKEN` in env is set and `-t TOKEN` is not specified, p.token (assigned `$PAGERDUTY_TOKEN` at l.32) is overwritten as "" in l.34.

fix to accept PAGERDUTY_TOKEN in env for PagerDuty

---

providers/aws/codebuild.go

When using `--resources=codebuild` I noticed the list was incomplete. Taking a look at the code the cause was that the output list was being overwritten on each page iteration instead of being appended. After refactoring the code all codebuild projects are showing correctly.

Fix aws codebuild pagination

---

terraformutils/connect_test.go
terraformutils/hcl.go

* Just a fix for the annoying bug #921
* Tested with `azurerm` provider.

hcl: fix for #921: 002D printed instead of hyphen

---

README.md
cmd/provider_cmd_opsgenie.go
cmd/root.go
docs/opsgenie.md
go.mod
go.sum
providers/opsgenie/opsgenie_provider.go
providers/opsgenie/opsgenie_service.go
providers/opsgenie/team.go
providers/opsgenie/user.go

This PR adds [Opsgenie](https://www.atlassian.com/software/opsgenie) as further provider with support of two basic resources/services for now:
* [opsgenie_team](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/team)
* [opsgenie_user](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/user)

Add "Opsgenie" as further provider

---

README.md
cmd/provider_cmd_mackerel.go
cmd/root.go
docs/mackerel.md
go.mod
go.sum
providers/mackerel/alert_group_setting.go
providers/mackerel/aws_integration.go
providers/mackerel/channel.go
providers/mackerel/downtime.go
providers/mackerel/mackerel_provider.go
providers/mackerel/mackerel_service.go
providers/mackerel/monitor.go
providers/mackerel/notification_group.go
providers/mackerel/role.go
providers/mackerel/service.go

This PR adds [Mackerel](https://en.mackerel.io/) as further provider. 
**Supported Services**
- [alert_group_setting](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/alert_group_setting)
- [aws_integration](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/aws_integration)
- [channel](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/channel)
- [downtime](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/downtime)
- [monitor](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/monitor)
- [notification_group](https://registry.terraform.io/providers/mackerelio-labs/mackerel/latest/docs/resources/notification_g …

Add “Mackerel” as further provider

---

.golangci.yml

The golint was officially deprecated.
golang/go#38968
>  The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."

ci: replace golint with revive

---

go.mod
go.sum

include release 5.2.0, 5.3.0
> Add support for modsec_rule_id filter parameter
> Add support for Link header pagination
> Add pagination support for GET /service endpoint
https://github.com/fastly/go-fastly/releases/tag/v5.2.0
https://github.com/fastly/go-fastly/releases/tag/v5.3.0

deps: go-fastly 5.3.0

---

terraformutils/walk.go
terraformutils/walk_test.go

Workaround for panic caused by an unexpected nested map instead of string.
Issues:
- #1166
- #1130
Workaround (not a solution, see note below):
- Add warning when nested element is map instead of string
- Add condition to prevent panic
Note: this is not a fix (as aws structure was updated and this needs to be reflected in code), but a workaround instead that only adds warning and prevents panic.

Workaround for issues #1166, #1130 import using aws provider fails

---

docs/octopus.md
providers/octopusdeploy/octopusdeploy_provider.go
providers/octopusdeploy/octopusdeploy_service.go

The doc didn't match the [supported services](https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/octopusdeploy/octopusdeploy_provider.go#L59).
The [official provider](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy#readme) expects `api_key` with the underscore.  It returns an "unexpected argument apikey" error otherwise.

Octopus deploy docs and provider argument name

---

docs/relic.md
go.mod
go.sum
providers/newrelic/alert.go

Following [New Relic terraform provider document](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition) ,  using `newrelic_nrql_alert_condition` resource is preferred to declare newrelic alert conditions.

newrelic - exporting nrql alert condition

---

terraformutils/hcl.go

During an import for aws glue resources, I had this error: `At 8:5: expected: IDENT | STRING | ASSIGN | LBRACE got: SUB`
The root cause is in aws_glue_job, default_parameters block can take keys that starts with `--`:
```
default_arguments = {
"--job-language" = "scala"
}
```
See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_job
Fixes #1208

fix: some hcl keys must be quoted

---

providers/azure/database.go

The iterator next call must be in the for loop

fix: remove the infinite loop on sql servers virtual network rules

---

README.md

Minor, link wouldn't resolve - "Page not found"
I guess registry.terraform.io dropped the .html at some point

fix broken link tf/aws/s3

---

providers/aws/s3.go

Buckets in us-east-1 end up with a null constraintString from GetBucketLocation, this results in missing all of these buckets in the current code.
Also add back aws_s3_bucket_policy terraform resource

Add support for s3 buckets in us-east-1

---

docs/okta.md

Fixed the typo for `okta_trusted_origin`
https://github.com/GoogleCloudPlatform/terraformer/blob/dd5512db1e7408e05e9f9a96b1f35c94ddf82587/providers/okta/trusted_origin.go#L33
https://github.com/GoogleCloudPlatform/terraformer/blob/d2916ad40b1767601537157aee36dfe6ce385503/providers/okta/okta_provider.go#L106

okta: fix typo for `okta_trusted_origin`

---

go.mod
go.sum

regression run against provider 3.12.0
release notes, https://github.com/DataDog/datadog-api-client-go/blob/master/CHANGELOG.md#1140--2022-05-18

deps(datadog): update datadog-api-client-go to v1.14.0

---

go.mod
go.sum

v6.3.2
Enhancements:
Add Backends field to Director https://github.com/fastly/go-fastly/pull/347
v6.2.0
Enhancements:
Origin Inspector: Get Historical Origin Metrics for a Service https://github.com/fastly/go-fastly/pull/335
v6.1.0
Enhancements:
Support Fastly-RateLimit-Remaining and Fastly-RateLimit-Reset https://github.com/fastly/go-fastly/pull/337
Stats: Add test for fetching stats by service and field https://github.com/fastly/go-fastly/pull/333

deps(fastly): update go-fastly to v6.3.2

---

docs/datadog.md

Timeboard and Screenboard are no longer supported after version 0.8.21

Removing timeboard and screenboard from datadog.md

---

docs/auth0.md

As noted in https://github.com/GoogleCloudPlatform/terraformer/issues/1383, this change updates the import command to work correctly with terraformer v0.8.21.

doc: update resources example

---

providers/ibm/ibm_provider.go
providers/ibm/ibm_secret_manager.go

Generated Tf file -
resource "ibm_resource_instance" "tfer--secrets_manager_yb_fpll" {
location = "eu-gb"
name = "Secrets Manager-yb"
plan = "trial"
resource_group_id = "834d7f416f2740f49dd7d2c2c7073253"
service = "secrets-manager"
timeouts {
create = "15m"
}
}
output.tf -
output "ibm_resource_instance_tfer--secrets_manager_yb_fpll_id" {
value = "${ibm_resource_instance.tfer--secrets_manager_yb_fpll.id}"
}

Added support for ibm secret manager

---

providers/aws/api_gateway.go

Fix the following error
`2022/09/08 06:24:56 [ERR]: duplicate resource found: aws_api_gateway_rest_api.tfer--SomeName`

Fix duplicate resource found error in aws_api_gateway_rest_api

---

cmd/import.go
terraformutils/hcl.go
terraformutils/hcl_test.go
terraformutils/terraformoutput/hcl.go

Disables sorting of resource lists, which is useful for cases where
remote order matters.

Add --no-sort flag to import

---

docs/heroku.md
providers/heroku/heroku_provider.go
providers/heroku/team_app.go

This adds a new resource for a Heroku `team_app`, as well as adding support for filtering team_apps that are selected as sources for Terraform generation.
If I can get this PR pushed through, I'd like to address https://github.com/GoogleCloudPlatform/terraformer/issues/1226 next.
FWIW, I'm part of Heroku, and I have some cycles I can spare to improve the Heroku provider, assuming I can get some eyes on my PRs to help get them in good shape for this project.
CC: @sergeylanzman

Add Heroku `team_app` resource

---

providers/aws/sg.go

This PR fixes the nil port error with FromPort and ToPort for aws provider sg

fix nil port error with FromPort and ToPort for aws provider sg

---

go.mod
go.sum

release notes in here, https://github.com/fastly/go-fastly/releases/
Verified with my local setup

deps: update to use go-fastly v6.8.0

---

providers/aws/cognito.go

Fix the duplicate resource error like the following,
```
[ERR]: duplicate resource found: aws_cognito_user_pool_client.tfer--XXXXX
```
`pool.IdentityPoolName`, `pool.Name` and `poolClient.ClientName` can be duplicated. This PR makes those values unique.

Fix duplicate resource errors in aws_cognito_*

---

docs/aws.md
providers/aws/iam.go

This RP is add support for AWS IAM Access Key.
* iam_access_key.tf
```
resource "aws_iam_access_key" "tfer--AKxxxxxxxxxxxxxxxxxx" {
depends_on = ["aws_iam_user.tfer--AIxxxxxxxxxxxxxxxxxx"]
status     = "Active"
user       = "user1"
}
```
* terraform.tfstate
```
{
"version": 4,
"terraform_version": "0.12.31",
"serial": 4,
"lineage": "38301e26-7037-fef0-c3e9-e7546311de19",
"outputs": {
"aws_iam_access_key_tfer--AKxxxxxxxxxxxxxxxxxx_id": {
"value": "AKxxxxxxxxxxxxxxxxxx",
"type": "string"
}
},
"resources": [
{
"mode": "managed",
"type": "aws_iam_access_key",
"name": "tfer--AKxxxxxxxxxxxxxxxxxx",
"provider": "provider.aws",
"instances": [
{
"schema_version": 0,
"attributes": {
"encrypted_secret": null,
"id": "AKxxxxxxxxxxxxxxxxxx",
"key_fingerprint": null,
"pgp_key": null,
"secret": null, …
```

feat: Add support for AWS IAM Access Key

---

docs/aws.md
providers/aws/lambda.go

This PR adds ability to import AWS Lambda permission resource (aws_lambda_permission).
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission
The exported HCL and state file will look like following:
```
resource "aws_lambda_permission" "tfer--lambda-aea1751c-e528-4a3d-877f-08e371f42135" {
action        = "lambda:InvokeFunction"
function_name = "arn:aws:lambda:us-east-1:11111111111111:function:test"
principal     = "events.amazonaws.com"
source_arn    = "arn:aws:events:us-east-1:1111111111111:rule/rule"
statement_id  = "lambda-aea1751c-e528-4a3d-877f-08e371f42135"
}
```
terraform.tfstate
```
"aws_lambda_permission.tfer--lambda-aea1751c-e528-4a3d-877f-08e371f42135": {
"type": "aws_lambda_permission",
"depends_on": [],
"primary": {
"id": …
```

Add aws_lambda_permission support

---

providers/aws/sg.go

`IpPermission.IpProtocol` can get the value "-1"
https://github.com/aws/aws-sdk-go-v2/blob/main/service/ec2/types/types.go#L7263-L7270
But when `IpPermission.IpProtocol` is "-1" then, the following panic occurs
```
2022/09/29 18:34:28 aws importing... sg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4d70abf]
goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.fromPort(...)
/home/runner/work/terraformer/terraformer/providers/aws/sg.go:362
```

Fix the following panic in aws security_group 

---

providers/keycloak/generator.go

Assign and access values in separate loops for `mapClientNames` and `mapClientClientNames` to avoid fetching with a non-existent key.
Before the fix I would randomly get empty role reference:
```hcl
resource "keycloak_openid_client_service_account_role" "tfer--openid_client_service_account_role_myrealm_role_test_realm_management_view_users" {
client_id               = "${keycloak_openid_client.tfer--openid_client_myrealm_realm_management.id}"
realm_id                = "${keycloak_realm.tfer--realm_myrealm.id}"
role                    = ""
service_account_user_id = "${keycloak_openid_client.tfer--openid_client_myrealm_role_test.service_account_user_id}"
}
```
After the fix it always has the correct value:
```hcl
resource "keycloak_openid_client_service_account_role" …
```

fix(keycloak): random empty role references

---

go.mod
providers/tencentcloud/clb.go
providers/tencentcloud/cvm.go
providers/tencentcloud/route_table.go
providers/tencentcloud/tencentcloud_provider.go

Additional features:
- fix clb listener id reference
- add more connections between resources

build(deps): bump github.com/tencentcloud/tencentcloud-sdk-go from v3.0.233 to v1.0.392

---

providers/aws/alb.go

This PR corrects the certificate listener id that needs to follow the format listener-arn_certificate-arn.
The community reports this issue several times : 
https://github.com/GoogleCloudPlatform/terraformer/issues/1199
https://github.com/GoogleCloudPlatform/terraformer/issues/1416

Bugfix - AWS certificate listener id need to follow the format 'listener-arn_certificate-arn'

---

docs/aws.md
go.mod
go.sum
providers/aws/aws_provider.go
providers/aws/medialive.go

Adds support for `medialive` resources:
- [aws_medialive_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel)
- [aws_medialive_input](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_input)
- [aws_medialive_input_security_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_input_security_group)
In order to be able to generate terraform files for medialive resources, the aws provider needs to be `~> 4.39.0` as that is when the resources was introduced [link](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.39.0).
E.g:
```tf
terraform {
required_version = ">= 1.3.5"
required_providers {
aws = {
source  = "hashicorp/aws"
version = "4.39.0"
}
}
} …
```

add support for aws_medialive_channel and input

---

build/multi-build/main.go

The "build for all providers" github action builds binaries only for the amd64 architecture. This PR changes that to allow creation of binaries across the board for all GOOS/GOARCH combinations.
While this commit registers as a rewrite (due to indentation changes), `git diff -w` gives a clearer picture of the change I've made:
```diff
samveen@zero2w:~/workspace/terraformer $ git diff -w HEAD^ HEAD |cat
diff --git a/build/multi-build/main.go b/build/multi-build/main.go
index e4dad148..8b6f3834 100644
--- a/build/multi-build/main.go
+++ b/build/multi-build/main.go
@@ -28,6 +28,7 @@ func main() {
allProviders = append(allProviders, providerName)
}
}
+	for _, arch :=  []string{"amd64", "arm64"} {
for _, OS := range []string{"linux", "windows", "mac"} {
for _, provider := range allProviders { …
```

Build provider binaries for all GOOS+GOARCH combinations

---

docs/datadog.md

An issue was raised (https://github.com/GoogleCloudPlatform/terraformer/issues/1605) regarding how to "_Import Datadog Monitors filtering on tags_".
This PR updates the [Datadog](https://www.datadoghq.com/) Terraformer docs with further information on:
- Installation/Setup
- Running Terraformer for importing Datadog resources
- Filtering resources

Additions to Datadog docs with filtering examples and setup

---

docs/aws.md
providers/aws/cloud_front.go

Hello.
I added AWS Cloudfront aws_cloudfront_cache_policy feature. (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_cache_policy)
After importing the cache policy resource, if there is an id that matches the cachebehavior of cloudfront_distribution, merge it.

add aws_cloudfront_cache_policy

---

providers/aws/cloud_front.go

I recently added AWS CloudFront CachePolicy and mapping to Distrubtion in the PostConvert Hook.
I overlooked that the id of cache behavior can be optional.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#cache_policy_id  
- Errors mapping distribution to policies in PostConvertHook
- The ID value in the Cache Behavior Arguments is optional and must be null checked (CachePolicy_id does not exist if the cache behavior is Legacy cache settings).
#1648, #1634

fix: cloudfront cachepolicy id mismatch

---

README.md

There are two distinct steps for installing Terraformer and Terraform platform plugins - this change aims to clarify these in the README.

Update README.md to clarify installation steps

---

docs/okta.md
providers/okta/authorization_server_policy_rule.go
providers/okta/okta_provider.go

This PR adds support to import Okta's authorization server policy rules.
[https://registry.terraform.io/providers/okta/okta/latest/docs/resources/auth_server_policy_rule](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/auth_server_policy_rule)
Exported example:
```
resource "okta_auth_server_policy_rule" "tfer--auth-server-default-policy-default-policy-rule-default-policy-rule" {
access_token_lifetime_minutes  = "60"
auth_server_id                 = "aus111111111111111"
grant_type_whitelist           = ["authorization_code", "client_credentials", "implicit", "password"]
group_whitelist                = ["EVERYONE"]
name                           = "Default Policy Rule"
policy_id                      = "00p222222222222222"
priority                       = "1" …
```

Added okta_auth_server_policy_rule support

---

go.mod
go.sum
providers/aws/aws_provider.go
providers/aws/identitystore.go

*Description*:
Update AWS provider to add support for resources [`aws_identitystore_*`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group).
Please note that it would be nice to use references in the `aws_identitystore_group_membership` resource toward the corresponding `aws_identitystore_group`  and `aws_identitystore_user`. However I do not know how to do that. Advice are welcome.

Adding Extraction of IdentityStore

---

docs/aws.md
go.mod
go.sum
providers/aws/redshift.go

In version `5.0.0` of the `terraform-provider-aws` the `aws_redshift_security_group` resource got deprecated.
In this PR the resource got removed and documentation got updated.
https://github.com/hashicorp/terraform-provider-aws/pull/30966
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0
This will also solve https://github.com/GoogleCloudPlatform/terraformer/issues/1718

Removed deprecated redshift resource

---

.github/workflows/release.yaml
.github/workflows/test.yml
go.mod

Bump to use the latest go, go1.20
go1.20 release notes, https://tip.golang.org/doc/go1.20

deps: bump to go1.20

---

providers/aws/batch.go

I tried to import AWS Batch job definition and got the following error.
```
2023/06/08 12:54:57 ERROR: Read resource response is null for resource aws_batch_job_definition.tfer--job_definition_name
2023/06/08 12:54:58 ERROR: Unable to refresh resource tfer--job_definition_name
```
It seems that `jobDefinitions` parameter in DescribeJobDefinitions API needs to include the revision of the job definition.
https://docs.aws.amazon.com/batch/latest/APIReference/API_DescribeJobDefinitions.html
This fix worked for me locally.

fix: importing aws_batch_job_definition

---

providers/opal/resource.go

Adds minor updates for the Opal provider:
- When permission sets are imported, we check the parent account and format the tf resource name as `{acc_name}_{permission_set_name}` so as to disambiguate across accounts
- Fixes a bug where if you have two resources called "x", and then another called "x_2", then two "x_2"s are created, leading to an import error. Instead, we disambiguate using a UUID prefix, which should likely not cause collisions.

Add support for AWS Identity Center in Opal provider

---

.github/workflows/release.yaml
.github/workflows/test.yml

fixes #1741 
Right now the windows build is completely broken due to the OOM issue, and it now blocks the new releases for 0.8.23 and 0.8.24. I would recommend removing the windows builds for now and we can always add them back later. (first report in https://github.com/GoogleCloudPlatform/terraformer/issues/1542)
cc @sergeylanzman

workflows: remove windows for ci and release

---

providers/aws/api_gateway.go

This PR allows us to generate api_gateway objects that won't collide with each other even if they don't uniquely hash the resource ids on the AWS API side.

fix: #1720 - api-gateway: qualify resource references

---

providers/aws/codebuild.go

Hi, I found a small bug while importing a codebuild project into terraformer, so I'm opening a PR. (Reopen)
- concurrent_build_limit value cannot be zero.  
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project  
- Remove it from the PostConvertHook step.
Issue https://github.com/GoogleCloudPlatform/terraformer/issues/1610

fix(aws): `concurrent_build_limit` cannot be zero

---

providers/aws/codecommit.go

This PR adds support to `aws_codecommit_approval_rule_template`
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_approval_rule_template#last_modified_user
Exported example:
```
resource "aws_codecommit_approval_rule_template" "tfer--codecommit_template_test" {
content = <<CONTENT
{
"DestinationReferences": [
"ref/master"
],
"Statements": [
{
"ApprovalPoolMembers": [
"CodeCommitApprovers:ss2"
],
"NumberOfApprovalsNeeded": 3,
"Type": "Approvers"
}
],
"Version": "2018-11-08"
}
CONTENT
description = "codecommit_template_test_Template"
name        = "codecommit_template_test"
}
```

Added codecommit approval rule template

---

providers/keycloak/generator.go

Hi!
This PR adds a check to ensure that the `role_ids` field is not `nil`. When running this against an empty realm I got a panic which this patch fixes:
```
panic: interface conversion: interface {} is nil, not []interface {}
goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/keycloak.(*RealmGenerator).PostConvertHook(0x140018ae0c0)
github.com/GoogleCloudPlatform/terraformer/providers/keycloak/generator.go:527 +0x51b0
...
```

Fix: Handle nil type during `keycloak_group_roles` processing

---

providers/aws/identitystore.go

Fix crashing on importing AWS identitystore, if there are no instances, reproduced on current master.
closes https://github.com/GoogleCloudPlatform/terraformer/issues/1808
```
terraformer import aws --resources=identitystore --regions=us-west-2
....
2023/12/11 20:06:06 aws importing... identitystore
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*IdentityStoreGenerator).GetIdentityStoreId(0xc0038b90d0?)
/Users/sergey/temp/terraformer/providers/aws/identitystore.go:44 +0x1ce
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*IdentityStoreGenerator).InitResources(0x0?)
/Users/sergey/temp/terraformer/providers/aws/identitystore.go:169 +0x25 …
```

Fix: AWS identitystore: failed if there are no instances

---

README.md

People were copying the line `export PROVIDER={all,google,aws,kubernetes}` as is and getting confused when only the kubernetes provider is available.  This uses `PROVIDER=all` as a sensible default and provides instructions for people who only want one provider.

Clarify installation instructions to avoid issue #470

---

docs/okta.md

It took me a while to get this running b/c if you give garbage config the code does DNS lookups for nonexistent domains and waits silently. `--verbose` helped me figure out what I had wrong by seeing nonsense URLs, but adding this clarity to the examples may prevent others having this problem.

Add more example details for Okta

---

providers/gcp/gcp_provider.go

adding a field mask to omit any unneeded information from regions.get response and improve latency

GCP provider: adding a field mask 

---

providers/azure/database.go

**Description**
This PR addresses the use of deprecated Azure resource names in the Azure database provider. The following updates have been made to align with the current resource naming standards:
Updated azurerm_sql_server to azurerm_mssql_server Updated azurerm_sql_database to azurerm_mssql_database Updated azurerm_sql_firewall_rule to azurerm_mssql_firewall_rule
**Motivation**
The existing resource names (azurerm_sql_) are deprecated in favor of azurerm_mssql_. This fix ensures compatibility with the latest Terraform provider updates and avoids the usage of deprecated resource names. This fix addresses the following problems:
panic: unknown resource type azurerm_sql_server
panic: unknown resource type azurerm_sql_database
panic: unknown resource type azurerm_sql_firewall_rule …

fix: updated deprecated resource names in azure database provider

---

providers/gcp/gcp_provider.go

🐛 (gcp/getRegion) handle regionName == "global"

---

docs/alicloud.md

Include a configuration example for users who prefer not to install the Alicloud client.

alicloud doc: add config example

---

docs/digitalocean.md
providers/digitalocean/digitalocean_provider.go
providers/digitalocean/vpc.go

Adds support for `vpc` resource:
- [digitalocean_vpc](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/vpc)

add support for digitalocean_vpc

---

providers/aws/aws_provider.go

This fixes issue number 1767 where terraformer
doesn't respect the AWS_PROFILE environment
variable when it is set.
[1]:https://github.com/GoogleCloudPlatform/terraformer/issues/1767

Honor AWS_PROFILE environment variable

---

go.mod
go.sum
providers/aws/dx.go

This pull request adds support for AWS Direct Connect resources in Terraformer, The following resources have been implemented:
1.	aws_dx_gateway: Direct Connect Gateways.
2.	aws_dx_private_virtual_interface: Private Virtual Interfaces.
3.	aws_dx_public_virtual_interface: Public Virtual Interfaces.
Fixes #1959

Fix: Add aws direct connect resources

---

go.mod
providers/alicloud/dns.go

Using terraform alidns resource instead of dns resource because of deprecation of dns resource in terraform provider

fix: updated deprecated alicloud_dns resources 

---

README.md

As shown in #1761, CF provider is broken. People approaching the tool for the first time might think CF will work, since it's in the supported providers list, only to discover later it's not the case. This is not faithful with current status.
To prevent others to stumble with this in the future, at least let's make it visible.

Docs: Show Cloudflare's provider status as broken

---

cmd/import.go

In `cmd/import.go`, there is an implementation that checks whether `Excludes` options is specified.
The default value for `options.Excludes` is `[]string{}` as you can see here:
https://github.com/GoogleCloudPlatform/terraformer/blob/a5b4b69b1cd36942ed85c1c6f8ba81e16b8b8a2b/cmd/import.go#L395-L410
However, the condition statement for checking `options.Excludes` is `if options.Excludes != nil`.
https://github.com/GoogleCloudPlatform/terraformer/blob/a5b4b69b1cd36942ed85c1c6f8ba81e16b8b8a2b/cmd/import.go#L127
As default value for `options.Excludes` is `[]string{}`, this always results true.
This should be fixed as `len(options.Excludes) > 0`
This does not cause panic when `option.Excludes` is false as you can see [here](https://go.dev/play/p/LgJNXCEBBHr)
You can see similar implementation …

nits: incorrect condition stmt for options.Excludes

---

providers/auth0/auth0_service.go
providers/aws/aws_provider.go
providers/aws/dx.go

This PR fixes a bug where Direct Connect Connections (dxcon-*) were being incorrectly categorized as Direct Connect Gateways (aws_dx_gateway) during resource generation. This mismatch caused downstream errors in Terraform due to invalid resource ID formats.
Also adds support for aws_dx_connection as it was missing in the command list.

Fix: Incorrect Resource Type for Direct Connect Connections

---

docs/ibmcloud.md
go.mod
go.sum
providers/ibm/ibm_cd_toolchain.go
providers/ibm/ibm_provider.go
providers/ibm/instance_groups.go

Includes changes from: https://github.com/GoogleCloudPlatform/terraformer/pull/2015 "Add support for ibm cd toolchain", which is using goroutines and mutexes.
Noticed that instance_groups.go is also using goroutines, but was not using a mutex, leading to the possibility of resources being overwritten. Changes in this PR include:
* Moving resourceMutex (which is used for g.Resources) from ibm_cd_toolchain.go to ibm_provider.go
* Adding resourceMutex to instance_groups.go

Fix ibm instance groups missing mutex
