GoogleCloudPlatform/terraformer

go.sum

fix for https://github.com/GoogleCloudPlatform/terraformer/issues/8
related https://github.com/golang/go/issues/29278

fix_checksum_mismatch_issue_8

---

go.mod
go.sum
vendor/golang.org/x/crypto/openpgp/keys.go
vendor/golang.org/x/crypto/openpgp/packet/packet.go
vendor/golang.org/x/crypto/openpgp/packet/private_key.go
vendor/golang.org/x/crypto/openpgp/packet/signature.go
vendor/golang.org/x/crypto/openpgp/packet/userattribute.go
vendor/golang.org/x/crypto/ssh/agent/client.go
vendor/golang.org/x/crypto/ssh/agent/keyring.go
vendor/golang.org/x/crypto/ssh/agent/server.go
vendor/golang.org/x/crypto/ssh/certs.go
vendor/golang.org/x/crypto/ssh/client.go
vendor/golang.org/x/crypto/ssh/keys.go
vendor/golang.org/x/crypto/ssh/server.go
vendor/modules.txt

https://github.com/GoogleCloudPlatform/terraformer/issues/11

Fix build after merge openstack

---

.travis.yml

fixes #12 
I added .travis.yml to do travis-ci on this repos.

add travis-ci support #12

---

README.md
providers/gcp/gke.go
terraform_utils/provider_wrapper/provider.go
tests/gcp/main.go

https://github.com/GoogleCloudPlatform/terraformer/issues/26

fix support gke

---

providers/gcp/gcs.go

add support:
google_storage_notification
google_storage_default_object_acl
TODO finish support google_storage_transfer_job

Refactor gcs

---

README.md
providers/gcp/gcp_provider.go
providers/gcp/pubsub.go

https://github.com/GoogleCloudPlatform/terraformer/issues/20

google: add pubsub support

---

providers/aws/route53.go

https://github.com/GoogleCloudPlatform/terraformer/issues/66

aws: route53, fix duplicate zone

---

README.md

Add documentation about filtering:
* Make some clarification about 'filter' word
* Explain where to find/check resources ID for filtering

doc: add documentation about filters and resources IDs

---

providers/aws/route53.go

AWS Route 53 zones and records describing API limits the number of exported resources to certain number (`100` for records) per request.
Thus we need to fire multiple requests to retrieve all the resources in a time.
This PR replaced the API call to `List***Pages` which iterates API requests until reaching to the last page.

Add paging support to AWS Route53 resource describing requests

---

README.md
terraform_utils/provider_wrapper/provider.go

Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/GoogleCloudPlatform/terraformer/issues/79

Use plugins relative to current directory

---

README.md

Relates to https://github.com/Homebrew/homebrew-core/pull/40632
Adding an installation option for Homebrew users. :)

Add Homebrew installation option

---

cmd/import.go
cmd/plan.go

fixed https://github.com/GoogleCloudPlatform/terraformer/issues/105
@ktogo FYI

fix plan bugs

---

providers/gcp/compute.go
providers/gcp/gcp_compute_code_generator/resources.go
providers/gcp/networkEndpointGroups_gen.go

https://github.com/GoogleCloudPlatform/terraformer/issues/103

gcp: add support google_compute_network_endpoint_group

---

README.md
providers/aws/aws_provider.go
providers/aws/ec2.go
providers/aws/igw.go
providers/aws/route53.go

https://github.com/GoogleCloudPlatform/terraformer/issues/102

aws: add ec2 instances

---

providers/gcp/clouddns.go

added zoneName preceding google_dns_record_set

---

providers/cloudflare/dns.go

[Fix #154 ](https://github.com/GoogleCloudPlatform/terraformer/issues/154) & add add logics to PostConvertHook

Fix #154 & add some logic to PostConvertHook for 'cloudflare_record'

---

README.md
providers/cloudflare/access.go
providers/cloudflare/cloudflare_provider.go

#162 
* `access`
* `cloudflare_access_application`

Add cloudflare 'access' service

---

terraform_utils/service.go

fix for https://github.com/GoogleCloudPlatform/terraformer/issues/153

make filter work as filter

---

README.md

This behaviour was changed in #157.

Update README.md to document new filtering behaviour

---

cmd/version.go
providers/gcp/autoscalers_gen.go
providers/gcp/disks_gen.go
providers/gcp/gcp_compute_code_generator/main.go
providers/gcp/instanceGroupManagers_gen.go
providers/gcp/instanceGroups_gen.go
providers/gcp/instances_gen.go
providers/gcp/networkEndpointGroups_gen.go
providers/gcp/nodeGroups_gen.go
providers/gcp/targetInstances_gen.go

fix for https://github.com/GoogleCloudPlatform/terraformer/issues/160 https://github.com/GoogleCloudPlatform/terraformer/issues/156

fix gcp zones bug

---

README.md
providers/aws/aws_provider.go
providers/aws/glue.go

Added support for AWS glue crawler.
#127

add support for AWS glue crawler

---

README.md
providers/aws/aws_provider.go
providers/aws/sns.go
providers/aws/sqs.go

Added AWS SQS + SNS support

---

providers/aws/aws_provider.go
providers/aws/aws_service.go

Fixed #188 although #199 still should be merged as well since that is the default behaviour of the AWS SDK.

Adjusted AWS credentials configuration

---

README.md
providers/aws/aws_provider.go
providers/aws/cloudtrail.go

Adds support for the [aws_cloudtrail](https://www.terraform.io/docs/providers/aws/r/cloudtrail.html) resource.

Add support for aws_cloudtrail

---

cmd/import.go
go.mod

fix for https://github.com/GoogleCloudPlatform/terraformer/issues/208

fix issue 208

---

providers/aws/alb.go
providers/gcp/bigquery.go

Update `NewResource` calls to `NewSimpleResource` where possible.

Refactor NewResource -> NewSimpleResource where applicable

---

README.md
providers/aws/aws_provider.go
providers/aws/kinesis.go

Adds support for the [aws_kinesis_stream](https://www.terraform.io/docs/providers/aws/r/kinesis_stream.html) resource.

add support for aws_kinesis_stream

---

main.go
providers/aws/ecs.go
terraform_utils/connect.go
terraform_utils/connect_test.go

Solved:
- AWS ECS resources import #210 
- AWS ALB resources import #209
- Trace and debug logs #197

fixed AWS ECS task definitions + connections, reduced logs

---

cmd/import.go
terraform_utils/flatmap.go
terraform_utils/resource.go
terraform_utils/utils.go

Implement Flatmap Parser

---

terraform_utils/hcl.go

Rewrite TfSanitize to Prevent Invalid Terraform Identifiers

---

providers/aws/aws_provider.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/209

fix issue 209

---

providers/aws/glue.go

This PR adds support for importing aws_glue_catalog_database resource.

add support for glue database

---

README.md
providers/aws/aws_provider.go
providers/aws/msk.go
terraform_utils/connect.go
terraform_utils/connect_test.go
terraform_utils/flatmap.go
terraform_utils/resource.go
terraform_utils/walk.go
terraform_utils/walk_test.go

Now it's possible to define connections that are placed in nested attributes

Refactored connections + added AWS MSK

---

README.md
providers/aws/aws_provider.go
providers/aws/budgets.go

Adds support for the [aws_budgets_budget](https://www.terraform.io/docs/providers/aws/r/budgets_budget.html) resource.

add support for aws_budgets_budget

---

README.md
providers/azure/azure_provider.go
providers/azure/disk.go
providers/azure/network_interface.go
providers/azure/network_security_group.go
providers/azure/storage_account.go
providers/azure/virtual_machine.go
providers/azure/virtual_network.go

Adds support for several Azure resources. List of resources added:
* `azurerm_managed_disk`
* `azurerm_network_interface`
* `azurerm_network_security_group`
* `azurerm_storage_account`
* `azurerm_virtual_machine`
* `azurerm_virtual_network`

Add support for Azure resources

---

README.md
providers/digitalocean/cdn.go
providers/digitalocean/digitalocean_provider.go
providers/digitalocean/droplet_snapshot.go
providers/digitalocean/ssh_key.go
providers/digitalocean/tag.go
providers/digitalocean/volume_snapshot.go

Adds support for several DigitalOcean resources. List of resources added:
* `digitalocean_cdn`
* `digitalocean_droplet_snapshot`
* `digitalocean_ssh_key`
* `digitalocean_tag`
* `digitalocean_volume_snapshot`

Add support for DigitalOcean resources

---

README.md
providers/alicloud/alicloud_provider.go
providers/alicloud/alicloud_service.go
providers/alicloud/ecs.go
providers/alicloud/pvtz.go
providers/alicloud/ram.go
providers/alicloud/rds.go
providers/alicloud/sg.go
providers/alicloud/slb.go

https://github.com/GoogleCloudPlatform/terraformer/issues/170

Minor fixes on Alicloud

---

README.md

Variable: PROVIDER
Should be:  ${PROVIDER}  or $PROVIDER

fixed: Installation / linux - ${PROVIDER}

---

providers/alicloud/ecs.go

Support tag filter for alicloud ecs.

alicloud ecs tag filter

---

terraform_utils/provider_wrapper/provider.go

Allow provider names as suggested by hashicorp

---

providers/aws/glue.go

This PR adds support for importing aws_glue_table resource.

add support for aws_glue_table

---

providers/alicloud/slb.go

AliCloud: Fixed SLB listeners

---

README.md
providers/aws/sqs.go

#291 sqs fix

---

README.md
providers/linode/domain.go
providers/linode/linode_provider.go
providers/linode/nodebalancer.go
providers/linode/rdns.go
providers/linode/stackscript.go

Adds support for the following Linode resources:
* `linode_domain_record`
* `linode_nodebalancer_config`
* `linode_nodebalancer_node`
* `linode_rdns`
* `linode_stackscript`

Add support for additional Linode resources

---

README.md
providers/vultr/firewall_group.go

Adds support for the [`vultr_firewall_rule`](https://www.terraform.io/docs/providers/vultr/r/firewall_rule.html) resource.

Add support for Vultr firewall rule

---

README.md
providers/digitalocean/database_cluster.go

Adds support for the [`digitalocean_database_connection_pool`](https://www.terraform.io/docs/providers/do/r/database_connection_pool.html) resource.

Add support for DigitalOcean database connection pool

---

README.md
cmd/provider_cmd_keycloak.go
cmd/root.go
go.mod
providers/keycloak/group.go
providers/keycloak/helpers.go
providers/keycloak/keycloak_provider.go
providers/keycloak/keycloak_service.go
providers/keycloak/openid_client.go
providers/keycloak/realm.go
providers/keycloak/role.go
providers/keycloak/scope.go
providers/keycloak/user.go

This PR will add the Terraformer provider for the Terraform Keycloak provider from mrparkers https://github.com/mrparkers/terraform-provider-keycloak.

Add Keycloak provider

---

providers/aws/lambda.go
terraform_utils/hcl.go

@meshuga 👀 
I think resource hacking need be in resource code, not in infrastructure code.
This PR resolve Lambda problem with other way in lambda PostConvertHook

Remove awsLambdaAdjustments

---

README.md
providers/azure/azure_provider.go
providers/commercetools/commercetools_provider.go
providers/keycloak/keycloak_provider.go

Alphabetizes existing services

Organize services

---

README.md
providers/github/organizationWebhooks.go
providers/github/teams.go

This pull request adds support for pagination on Github webhook and teams import.
I used the same configuration as repositories & members of 100 items per page.
This is a recreation of 2 previous PRs because of a bug in reviewdog, which was picking up one of my old branches.
Thanks for taking a look at my PR!

Add pagination for remaining supported GitHub resources

---

terraform_utils/flatmap.go

fix for https://github.com/GoogleCloudPlatform/terraformer/issues/365

fix issue 365

---

README.md
providers/aws/iam.go
tests/aws/main.go

Apart from that:
1. Fixed IAM Roles fetching
2. Removed incorrect IAM Group Membership setup - previously it wasn't working, so an additional code is needed to collect users associated with groups and build correct `aws_iam_group_membership ` resources
closes #358

Added IAM Instance Profile

---

README.md
providers/aws/aws_provider.go
providers/aws/codebuild.go

Adds support for the [`aws_codebuild_project`](https://www.terraform.io/docs/providers/aws/r/codebuild_project.html) resource.

add support for aws_codebuild_project

---

terraform_utils/terraform_output/bucket.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/381

fix bucket.tf

---

README.md
providers/aws/aws_provider.go
providers/aws/codedeploy.go

Adds support for the [`aws_codedeploy_app`](https://www.terraform.io/docs/providers/aws/r/codedeploy_app.html) resource.

add support for aws_codedeploy_app

---

README.md
providers/aws/aws_provider.go
providers/aws/eni.go

ENI - Elastic Network Interface

Adds support for the aws_network_interface resource 

---

providers/keycloak/group.go
providers/keycloak/openid_client.go
providers/keycloak/realm.go
providers/keycloak/role.go
providers/keycloak/scope.go

Hi,
Without this, if you run terraformer multiple times, you don't get the same results.
Regards,
Pierre

feat/keycloak: sort slices to get predictable results

---

README.md

#331 adjusted filter docs

---

README.md
providers/aws/aws_provider.go
providers/aws/ecr.go

#394 AWS ECR

---

README.md
providers/aws/acm.go
providers/aws/aws_provider.go
providers/aws/budgets.go
providers/aws/cloud9.go
providers/aws/cloudtrail.go
providers/aws/cloudwatch.go
providers/aws/codebuild.go
providers/aws/ebs.go
providers/aws/eip.go
providers/aws/firehose.go
providers/aws/igw.go
providers/aws/kinesis.go
providers/aws/nat_gateway.go
providers/aws/route53.go
providers/aws/route_table.go
providers/aws/s3.go
providers/aws/sns.go
providers/aws/vpc_peering.go

Added AWS CloudWatch resources; small code refactoring

---

providers/aws/cloudformation.go

AWS CloudFormation fixes

---

README.md
cmd/import.go
providers/kubernetes/kubernetes_provider.go
terraform_utils/json.go
terraform_utils/provider_wrapper/provider.go
terraform_utils/resource.go
terraform_utils/service.go
terraform_utils/terraformer_string/string.go
terraform_utils/utils.go
tests/aws/main.go

Related to #401
The PR allows also to import all provider resources, with `*`.

Performance improvements, escaping fix for CF templates

---

README.md
providers/aws/api_gateway.go
providers/aws/aws_provider.go

AWS API Gateway

---

go.mod
providers/aws/cloudformation.go
terraform_utils/hcl.go

Fixed CF interpolation as well as HCL hacks to properly format singleton lists.
closes #420

#420 fixed CF interpolation; fixed HCL hacks

---

providers/aws/cloudformation.go

Bring back reference to CF resource by its identifier

---

README.md

Add Chocolatey Installation option for windows users
Some of us have to unfortunately use windows, lets at least make it comfortable!

Add Chocolatey Installation Option

---

README.md
providers/aws/aws_provider.go
providers/aws/qldb.go

Adds support for the [`aws_qldb_ledger`](https://www.terraform.io/docs/providers/aws/r/qldb_ledger.html) resource.

add support for aws_qldb_ledger

---

providers/gcp/gcp_compute_code_generator/resources.go
providers/gcp/instances.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/443 https://github.com/GoogleCloudPlatform/terraformer/issues/399

Fix gcp instances import

---

providers/gcp/cloudsql.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/429

gcp: fix cloudsql import

---

providers/aws/alb.go

Fixed default cert import to AWS ALB listener

---

README.md
providers/aws/aws_provider.go
providers/aws/sfn.go
vendor/modules.txt

https://www.terraform.io/docs/providers/aws/d/sfn_activity.html#
```
❯ ./terraformer import aws --resources sfn --regions ap-southeast-1                              
2020/03/30 18:25:03 aws importing region ap-southeast-1                                          
2020/03/30 18:25:03 aws importing... sfn                                
2020/03/30 18:25:08 Refreshing state... aws_sfn_state_machine.tfer--HelloWorld        
2020/03/30 18:25:08 Refreshing state... aws_sfn_activity.tfer--testSctivity                                         
2020/03/30 18:25:09 aws Connecting....                                                                                     
2020/03/30 18:25:09 aws save sfn …
```

Add import support for aws_sfn_*

---

providers/aws/sg.go

It's AWS issue to return data in unordered manner but fortunately, that's fine to pass data in random order to AWS.
closes #469

Added sorting of SGs and rules

---

README.md
cmd/provider_cmd_gmailfilter.go
cmd/root.go
providers/gmailfilter/filter.go
providers/gmailfilter/gmailfilter_provider.go
providers/gmailfilter/gmailfilter_service.go
providers/gmailfilter/label.go

This PR adds support for the GmailFilter provider.
https://github.com/yamamoto-febc/terraform-provider-gmailfilter

Add GmailFilter provider

---

go.mod
go.sum
providers/keycloak/authentication.go
providers/keycloak/generator.go

I added support for the following resource types of keycloak provider.
- `keycloak_authentication_flow`
- `keycloak_authentication_subflow`
- `keycloak_authentication_execution`
- `keycloak_authentication_execution_config`

feat: add support for keycloak authentication flow

---

README.md
providers/cloudflare/cloudflare_service.go
providers/cloudflare/firewall.go

Fix #516 
Support import Access Rule with account & zone scope

Support import 'cloudflare_access_rule' account & zone scope

---

README.md
providers/cloudflare/account_member.go
providers/cloudflare/cloudflare_provider.go
providers/cloudflare/firewall.go
providers/cloudflare/page_rule.go

Add more cloudflare resources
* `firewall`
* `cloudflare_rate_limit`
* `page_rule`
* `cloudflare_page_rule`
* `account_member`
* `cloudflare_account_member`

Add more cloudflare resources

---

providers/digitalocean/digitalocean_provider.go
providers/fastly/fastly_provider.go
providers/heroku/heroku_provider.go
providers/linode/linode_provider.go
providers/mikrotik/mikrotik_provider.go
providers/octopusdeploy/octopusdeploy_provider.go
providers/vultr/vultr_provider.go

remove {apiKey,token,password} from the provider output

---

README.md
go.mod
go.sum
providers/fastly/fastly_provider.go
providers/fastly/user.go

This PR did:
- bump the go-fastly to the latest version
- add fastly_user_v1 resource support

Add fastly user support

---

providers/gcp/bigquery.go

fix for https://github.com/GoogleCloudPlatform/terraformer/issues/482

gcp: fix bigquery import

---

README.md
providers/keycloak/openid_client.go

Hi, i added management for the following keycloak mappers : 
- user realm role mapper
- user client role mapper
- user session note mapper
- hardcoded role mapper
I also prepared code for further developments.

Add realm-role, client-role and session note mappers

---

cmd/version.go

relates to Homebrew/homebrew-core#56767

fix: update version field

---

go.mod
go.sum

bump terraform to the latest, this is the trivial change on the terraform side though.
Would impact the version listed in the generated tfstate file :)

chore(deps): bump tf to v0.12.28

---

README.md
providers/aws/sg.go

#493 split sg and rules

---

README.md
go.mod
go.sum
providers/azure/azure_provider.go
providers/azure/security_center_contact.go
providers/azure/security_center_subscription_pricing.go
providers/azure/storage_blob.go
providers/azure/storage_container.go

Added:
- azurerm_storage_container
- azurerm_storage_blob
- azurerm_security_center_contact
- azurerm_security_center_subscription_pricing

Added azure storage and security center resources 

---

README.md
providers/aws/aws_provider.go
providers/aws/workspaces.go

Adds support for the [aws_workspaces_directory](https://www.terraform.io/docs/providers/aws/r/workspaces_directory.html) resource.

add support for aws_workspaces_directory

---

README.md
providers/aws/workspaces.go

Adds support for the [aws_workspaces_workspace](https://www.terraform.io/docs/providers/aws/r/workspaces_workspace.html) resource.

add support for aws_workspaces_workspace

---

README.md
providers/azure/azure_provider.go
providers/azure/dns.go

```
azurerm_dns_ns_record.tfer---0040-: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/dnszones/dsadsadasfsafdsfsdfdsfds.dsadasd/NS/@]
azurerm_dns_txt_record.tfer--test-002D-txt: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/dnszones/dsadsadasfsafdsfsdfdsfds.dsadasd/TXT/test-txt]
azurerm_dns_mx_record.tfer--test-002D-mx: Refreshing state... [id=/subscriptions/8f9a5467-a960-422a-8e53-c899499da131/resourceGroups/rg1/providers/Microsoft.Network/dnszones/dsadsadasfsafdsfsdfdsfds.dsadasd/MX/test-mx]
azurerm_dns_srv_record.tfer--_test-002D-srv-002E-_dsa-002E-dsadsa: Refreshing state... …
```

Add azurerm_dns* support

---

providers/gcp/gcs.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/559

fix issue 559

---

providers/aws/aws_facade.go
providers/aws/eni.go
providers/aws/es.go

adjusted attribute filtering; improved unavailable service detection

---

cmd/import.go

The provider wrapper is used as an immutable object during importing.
There is no need to repeatedly launch and kill it in each iteraton on
services.
This will brings big performance improvement on some of the provider
, which will do some heavy-lift on initialization. For example, azurerm
provider will do auto registering resource providers on start up, which
will take about 10 seconds. For commands that specify a `-r "*"`,
terraformer will iterate each supported services, and each one will
take 10 seconds, which ends up to be a fairly long interval.

Import: avoid repeatedly (de)init provider wrapper

---

providers/azure/azure_provider.go

Add basic connection info for azure provider.

azure: add basic connection info

---

providers/datadog/synthetics.go

This PR adds support for filtering datadog synthetics by id and updates the api client to use the supported datadog go client.

Add filter support to datadog synthetic

---

providers/datadog/user.go

This PR adds support for filtering datadog users by id and updates the api client to use the supported datadog go client.

Add filter support to datadog user

---

providers/gcp/bigquery.go
providers/gcp/cloudFunctions.go
providers/gcp/clouddns.go
providers/gcp/dataproc.go
providers/gcp/gcs.go
providers/gcp/iam.go
providers/gcp/kms.go
providers/gcp/memoryStore.go
providers/gcp/pubsub.go
providers/gcp/schedulerJobs.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/627
fix https://github.com/GoogleCloudPlatform/terraformer/issues/607

replace log.fatal

---

terraformutils/terraformoutput/bucket.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/625

fix issue 652

---

providers/azure/network_security_group.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/580

azure: fix azurerm_network_security_group name

---

README.md
providers/aws/workspaces.go

Adds support for the [aws_workspaces_ip_group](https://www.terraform.io/docs/providers/aws/r/workspaces_ip_group.html) resource.

add support for aws_workspaces_ip_group

---

cmd/import.go

Continue on service error

---

terraformutils/hcl.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/595

don't crash on duplicate resources name

---

providers/gcp/instances.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/621

fix gcp instances  issue

---

README.md
providers/aws/aws_provider.go
providers/aws/efs.go

Added AWS EFS

---

README.md

Currently the README has some layout issue

docs: fix readme layout issue

---

README.md

formatting is correct this time :)

added resources and excludes parameter documentation

---

README.md
providers/azure/azure_provider.go
providers/azure/redis.go

Adds support for Azure Redis Cache.
@juno-yu Since there is no `tests` for Azure here in the project, would you have some time to please help out testing this? I'm not sure if I did it right.
Thank you

Add Azure (Redis Cache) support

---

providers/gcp/gke.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/655

google: fix gke

---

README.md
providers/aws/aws_provider.go
providers/aws/logs.go

Adding @mikeurbanski1 's contribution to the main fork as well

Add cloudwatch log group terraforming

---

README.md
providers/aws/aws_provider.go
providers/aws/cloudhsm.go

added CloudHSM

---

README.md
providers/datadog/dashboard_list.go
providers/datadog/datadog_provider.go

This PR adds support for the following Datadog resources:
- datadog_dashboard_list

Add support for datadog dashboard_list resource

---

terraformutils/hcl.go

style: fix typo

---

README.md
providers/datadog/datadog_provider.go
providers/datadog/metric_metadata.go

This PR adds support for the following Datadog resources:
- datadog_metric_metadata

Add support for datadog metric_metadata resources

---

providers/datadog/security_monitoring_default_rule.go
providers/datadog/security_monitoring_rule.go

This PR adds support for paginated endpoints for the datadog security monitoring resources

Add paginated endpoint support for datadog security resources

---

providers/aws/ec2.go

Fixed EC2 IOPS and throughput configuration

---

README.md
go.sum
providers/aws/s3.go
terraformutils/resource.go
terraformutils/service.go
terraformutils/service_test.go
terraformutils/walk.go
terraformutils/walk_test.go

#756 added support for a field only filtering

---

providers/datadog/role.go

Resolves https://github.com/GoogleCloudPlatform/terraformer/issues/799

Add pagination support for Datadog role resource

---

providers/datadog/monitor.go

Add paginated endpoint support for monitors resource

Add paginated endpoint support for Datadog monitors resource

---

README.md

add stargazers chart for fun :)

doc: add stargazers chart

---

terraformutils/providers_mapping.go

To address https://github.com/GoogleCloudPlatform/terraformer/issues/793#issuecomment-793733971 and restore filtering in terraformer.

Refreshing provider mapping after applied filters (filters regression)

---

providers/kubernetes/kind.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/838

 fix issue 838

---

README.md
cmd/provider_cmd_xenorchestra.go
cmd/root.go
go.mod
go.sum
providers/xenorchestra/acls.go
providers/xenorchestra/resource_sets.go
providers/xenorchestra/xenorchestra_provider.go
providers/xenorchestra/xenorchestra_service.go

This adds support for the xenorchestra terraform provider (web UI on top of Citrix hypervisor / XCP-ng) I develop. This PR initially supports the acl and resource_set resources but I intend to add further support for VMs, networks, storage repositories, etc.
Ran the following commands and verified the output files look correct.
```
ddelnano@ddelnano-desktop:~/code/terraformer$ ./terraformer import xenorchestra -r=acl
2021/03/31 22:14:59 xenorchestra importing... acl
2021/03/31 22:15:00 xenorchestra done importing acl
2021/03/31 22:15:00 Number of resources for service acl: 1
2021/03/31 22:15:00 Refreshing state... xenorchestra_acl.tfer--T7p2Rw
2021/03/31 22:15:00 Filtered number of resources for service acl: 1
2021/03/31 22:15:00 xenorchestra Connecting....
2021/03/31 22:15:00 …
```

Implement support for the terraform-provider-xenorchestra

---

README.md
cmd/provider_cmd_newrelic.go
providers/newrelic/newrelic_provider.go
providers/newrelic/newrelic_service.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/843

fix newrelic v2

---

README.md
go.mod
go.sum
providers/aws/aws_provider.go
providers/aws/ecr.go
providers/aws/ecrpublic.go
providers/aws/ssm.go
providers/xenorchestra/acls.go
tests/aws/main.go

#511 ECR adjustments, added ECR public and SSM PS

---

providers/alicloud/alicloud_provider.go

alicloud: fixes the nil pointer when importing the alicloud resources and supports global region

---

docs/gcp.md

This resolves Issue #777 by adding some documentation to the Google Cloud process.

doc: update credential information

---

providers/aws/route53.go

Fixed route53

---

cmd/provider_cmd_github.go
docs/github.md
providers/github/github_provider.go
providers/github/github_service.go
providers/github/members.go
providers/github/organizationWebhooks.go
providers/github/organization_block.go
providers/github/organization_project.go
providers/github/repositories.go
providers/github/teams.go
providers/github/user_ssh_keys.go

fix https://github.com/GoogleCloudPlatform/terraformer/issues/187

add support enterprise github

---

.github/workflows/release.yaml

added build step to release binary for darwin/arm64.

add apple silicon release binaries

---

docs/commercetools.md
go.mod
go.sum
providers/commercetools/api_extension.go
providers/commercetools/channel.go
providers/commercetools/commercetools_provider.go
providers/commercetools/custom_object.go
providers/commercetools/product_type.go
providers/commercetools/shipping_method.go
providers/commercetools/shipping_zone.go
providers/commercetools/state.go
providers/commercetools/store.go
providers/commercetools/tax_category.go
providers/commercetools/types.go

- Add commercetools `custom_object` resource
- Upgrade `commercetools-go-sdk` to `v0.3.1` adapting the code accordingly (needed for custom_object.)
- Improve README, including optional variables, which in my case I needed to use different values so it should be useful for others to know about them.

Add commercetools custom_object resource

---

docs/commercetools.md

Scope of changes is restricted to docs only.

fix(docs): corrects typo in project documentation

---

docs/aws.md
providers/aws/glue.go

Supported
- aws_glue_job https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_job
- aws_glue_trigger https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_trigger

Support awg_glue_job, aws_glue_trigger

---

go.mod
go.sum
providers/github/github_provider.go
providers/github/github_service.go
providers/github/members.go
providers/github/organizationWebhooks.go
providers/github/organization_block.go
providers/github/organization_project.go
providers/github/repositories.go
providers/github/teams.go
providers/github/user_ssh_keys.go
terraformutils/providerwrapper/provider.go

fix bugs
update to v35
fix https://github.com/GoogleCloudPlatform/terraformer/issues/902

fix github provider

---

go.mod
go.sum
providers/fastly/service_v1.go
providers/fastly/user.go

fastly: update to use fastly v3 api

---

README.md
cmd/provider_cmd_panos.go
cmd/root.go
docs/panos.md
go.mod
go.sum
providers/panos/device_config.go
providers/panos/firewall_networking.go
providers/panos/firewall_objects.go
providers/panos/firewall_policy.go
providers/panos/helpers.go
providers/panos/panos_provider.go
providers/panos/panos_service.go

This PR adds support for the PAN-OS Terraform Provider. It works only with firewalls for the moment, not Panorama. I didn't test it in an environment with VSYS.

Add panos provider

---

providers/panos/device_config.go

Small fix: name of the panos_telemetry resource.

fix(panos): telemetry name

---

providers/aws/cognito.go

Add support for importing AWS Cognito user pool clients.
I noticed that using that when I imported Cognito related objects to TF, user pool clients were not imported.
Tested against account in `eu-central-1` region with multiple user pool clients. Worked for me without issues.

Import aws_cognito_user_pool_client

---

docs/azure.md
providers/azure/azure_provider.go
providers/azure/data_factory.go
terraformutils/hcl.go

Currently exporting all resources handled by versions:
``` sh
$ terraform --version
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0
```
Please share your comments.

Support for azurerm import data factory

---

SECURITY.md

Adding security policy using go.co/vulnz.

Adding security policy.

---

.gitignore
providers/pagerduty/escalation_policy.go
providers/pagerduty/ruleset.go
providers/pagerduty/schedule.go
providers/pagerduty/service.go
providers/pagerduty/team.go
providers/pagerduty/user.go

This pull request also fixes pagerduty_service_event_rule resources not being created properly

 Fixed Offset not increasing when fetching Pagerduty API

---

providers/github/github_organization.go
providers/github/github_provider.go
providers/github/github_service.go
providers/github/members.go
providers/github/organization_block.go
providers/github/organization_project.go

I would like to have these terraform resources in the same state file so I reuse other terraformer resources code to enable this.

Add organization resource to be able to have members, blocked users and organization projects in the same state file.

---

docs/okta.md
providers/okta/factor.go
providers/okta/network_zone.go
providers/okta/okta_provider.go

* Add okta_network_zone
* Add okta_factor

Add more okta resource

---

go.mod
go.sum
providers/okta/authorization_server_policy.go

* Update go.mod
* Fix new reference releted ListAuthorizationServerPolicies() function

Bump okta-sdk-golang to v2.6.1

---

docs/okta.md
providers/okta/idp_oidc.go
providers/okta/idp_saml.go
providers/okta/idp_social.go
providers/okta/okta_provider.go

* Add okta_idp_oidc
* Add okta_idp_saml
* Add okta_idp_social

Add okta idp resources

---

providers/azure/azure_provider.go
providers/azure/data_factory.go
providers/azure/databricks.go
providers/azure/helper.go

New features:
- add `databricks` support
- updated `data_factory` resources exported
- refactorings with shared code

azurerm add databricks support

---

docs/azure.md
go.mod
go.sum
providers/azure/azure_provider.go
providers/azure/cosmosdb.go
providers/azure/data_factory.go
providers/azure/databricks.go
providers/azure/eventhub.go
providers/azure/helper.go
providers/azure/purview.go
providers/azure/synapse.go

Changes: 
* added synapse eventhub purview
* upgraded azure-sdk-for-go to v57.1.0
* fixed cosmodb API changes between v42 and v57
* updated data_factory docs

azurerm: added synapse eventhub purview

---

docs/azure.md
providers/azure/azure_provider.go
providers/azure/private_endpoint.go

- azurerm: added private_endpoint
- [azurerm_private_endpoint](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint)
- [azurerm_private_link_service](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_link_service)

azurerm: added private_endpoint

---

docs/azure.md
providers/azure/azure_provider.go
providers/azure/subnet.go
providers/azure/virtual_network.go

* Inspired by #585 
* Supporting:
* `azurerm_subnet`
* `azurerm_subnet_service_endpoint_storage_policy`
* `azurerm_subnet_nat_gateway_association`
* `azurerm_subnet_route_table_association`
* `azurerm_subnet_network_security_group_association`

azurerm: added subnet and  related

---

providers/azure/azure_provider.go
providers/azure/databricks.go
providers/azure/eventhub.go
providers/azure/network_security_group.go
providers/azure/private_endpoint.go
providers/azure/purview.go
providers/azure/subnet.go
providers/azure/synapse.go

* Currently there are resource connections only for `resource_group`.
* Added connections for properties with available resource mapping
* Fixed some resource names to honor the real name and match property connection properly

azurerm: improve resource connections

---

cmd/provider_cmd_azuredevops.go
cmd/root.go
docs/azuredevops.md
go.mod
go.sum
providers/azuredevops/azuredevops_provider.go
providers/azuredevops/azuredevops_service.go
providers/azuredevops/git_repository.go
providers/azuredevops/group.go
providers/azuredevops/helpers.go
providers/azuredevops/project.go

- Based on [Azure DevOps provider](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs) version v0.17
- Using Go [wrapper](https://github.com/microsoft/azure-devops-go-api) over [Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops)
- Basic scaffolding and a few services

azuredevops: new provider

---

README.md
docs/azure.md
providers/azure/azure_provider.go
providers/azure/data_factory.go
providers/azure/databricks.go
providers/azure/eventhub.go
providers/azure/management_lock.go
providers/azure/network_security_group.go
providers/azure/network_watcher.go
providers/azure/private_endpoint.go
providers/azure/purview.go
providers/azure/route_table.go
providers/azure/ssh_public_key.go
providers/azure/subnet.go
providers/azure/synapse.go

- azurerm: added [management_lock](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_lock)
- azurerm: added [ssh_public_key](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/ssh_public_key)
- azurerm: added [network_watcher](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_watcher)
- azurerm: added [network_security_rule](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule)
- azurerm: added [route_table](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/route_table)
-  azuredevops: added link on README.md

azurerm: added support for some networking resouces

---

go.mod
go.sum

deps: go-fastly 3.12.0

---

providers/azure/azure_provider.go
providers/azure/azure_service.go
providers/azure/synapse.go

* azurerm: more resource connections
* azurerm: fix azurerm_synapse_managed_private_endpoint
* azurerm: refactorings

azurerm: misc improvements

---

go.mod
go.sum
providers/okta/app.go
providers/okta/app_user_schema.go
providers/okta/factor.go
providers/okta/helpers.go
providers/okta/network_zone.go
providers/okta/okta_provider.go
providers/okta/okta_service.go
providers/okta/user_schema.go

Add okta_user_schema_property
Add okta_user_base_schema_property
Add okta_app_user_schema_property
Add okta_app_user_base_schema_property
Add okta_factor_totp
Update okta_factor

Add Okta Schema, TOTP, App Schema resources

---

docs/aws.md
go.mod
go.sum
providers/aws/rds.go

Adds the ability to import RDS clusters, along side the cluster members. Couldn't quite get the cluster endpoint import working, so that will have to wait.

aws: import rds clusters

---

.github/workflows/test.yml
docs/aws.md

Added more examples to import ec2 instances based on Instance Id and Name

Added more examples to import ec2 instances based on Instance Id and Name

---

providers/azure/azure_service.go
providers/azure/helper.go
providers/azure/route_table.go

Added Duplicate check method to avoid error having same name in different Resource group or at sub level

Update azure_service.go for fixing #1126Azure|| route_table ||[ERR]: duplicate resource found: azurerm_route.tfer--

---

providers/panos/firewall_networking.go
providers/panos/firewall_objects.go
providers/panos/helpers.go
providers/panos/panorama_networking.go
providers/panos/panorama_objects.go
providers/panos/panorama_plugins.go
providers/panos/panos_service.go

fixes https://github.com/GoogleCloudPlatform/terraformer/issues/1085, and adds tests everytime an assert is used.

feat: improve PANOS provider reliability

---

providers/gcp/cloudtasks.go
providers/gcp/gcp_provider.go

Add support for Google Cloud Tasks queues

add cloudtasks support

---

go.mod
go.sum

fix couple of bugs
- Do not omit zero int values on create operations fastly/go-fastly#318
- Fix len < 0 in test: len cannot return negative values fastly/go-fastly#319

deps(fastly): go-fastly 5.1.3

---

docs/azuredevops.md
providers/azuredevops/azuredevops_provider.go
providers/azuredevops/azuredevops_service.go
providers/azuredevops/git_repository.go
providers/azuredevops/group.go
providers/azuredevops/helpers.go
providers/azuredevops/project.go

fixed typos

---

providers/yandex/compute_disk.go
providers/yandex/compute_instance.go
providers/yandex/yandex_provider.go
providers/yandex/yandex_service.go

Make available new auth methods like in Terraform provider for Yandex Cloud
Also close #565

Support all available Yandex Cloud API auth methods

---

README.md
cmd/provider_cmd_azuread.go
cmd/root.go
docs/azuread.md
go.mod
go.sum
providers/azuread/app_role_assignment.go
providers/azuread/application.go
providers/azuread/azuread_provider.go
providers/azuread/azuread_service.go
providers/azuread/group.go
providers/azuread/service_principal.go
providers/azuread/user.go

This is my first time creating a provider and also coding in go. I hope, this PR will be useful for everyone. I will be happy to see reviews :D Thanks in advance.

add azuread provider

---

go.mod
go.sum

Bump Datadog API Client to latest version

---

go.mod
go.sum
providers/ns1/monitoringjob.go
providers/ns1/team.go
providers/ns1/zone.go

Hi, I fixed up the ns1 importer and added support for zone records. I don't have much experience with golang or terraform, so apologies for any bugs & non ideomatic code in this pr

Fix ns1 importer & add support for zone records

---

docs/ibmcloud.md
go.mod
go.sum
providers/ibm/cis.go
providers/ibm/cloud_functions.go
providers/ibm/cloud_log_analysis.go
providers/ibm/cloud_log_atracker.go
providers/ibm/cloud_watson_machine_learning.go
providers/ibm/cloud_watson_studio.go
providers/ibm/ibm_provider.go

Changes:
IBM: Add cloud observability service support(LogDNA, Activity Tracker)
IBM: Add Watson Studio, Watson Machine Learning support

Add ibm cloud observability service support

---

providers/datadog/datadog_provider.go
providers/datadog/logs_metric.go

closes: https://github.com/GoogleCloudPlatform/terraformer/issues/1511

[datadog_provider] Add support for logs_metric resource

---

docs/aws.md

- fix reference for `glue_crawler`

docs(aws): fix reference

---

providers/ibm/container_cluster.go
providers/ibm/cos.go
providers/ibm/ibm_is_security_group.go
providers/ibm/ibm_is_vpn_gateway.go

Changes:
Container Cluster: Added `hardware` and `datacenter` attribute
COS: Added `force_delete` attribute
Security Group Rule: Updated resource name
VPN Gateway: Updated resource connection

Added attributes to container cluster, cos and VPC resources

---

docs/aws.md
providers/aws/api_gateway.go

added: aws_api_gateway_api_key support

added: aws_api_gateway_api_key

---

go.mod
go.sum
providers/fastly/service_v1.go
providers/fastly/tls_subscription.go
providers/fastly/user.go

tested and verified in my setup

deps(fastly): bump to use go-fastly v7

---

providers/aws/nacl.go

Adds support for the `aws_default_network_acl`.

default network acl

---

docs/aws.md
providers/aws/rds.go

aws(rds): support `aws_rds_global_cluster`, `aws_db_snapshot`, `aws_db_cluster_snapshot`

---

providers/rabbitmq/binding.go
providers/rabbitmq/helpers.go

Changes needed to solve the problem indicated in the issue #1660.
These changes solve the problems indicated in the issue. 
As we can see in the following execution:
```
❯ terraformer import rabbitmq --resources=bindings,exchanges,permissions,policies,queues,users,vhosts
2023/03/07 13:46:35 rabbitmq importing... bindings
2023/03/07 13:46:36 rabbitmq done importing bindings
2023/03/07 13:46:36 rabbitmq importing... exchanges
2023/03/07 13:46:37 rabbitmq done importing exchanges
2023/03/07 13:46:37 rabbitmq importing... permissions
2023/03/07 13:46:37 rabbitmq done importing permissions
2023/03/07 13:46:37 rabbitmq importing... policies
2023/03/07 13:46:37 rabbitmq done importing policies
2023/03/07 13:46:37 rabbitmq importing... queues
2023/03/07 13:46:38 rabbitmq done importing queues …
```

fix(rabbitmq): fix rabbitmq problems in policies and bindings #1660

---

providers/tencentcloud/gaap.go

fix: update gaap

---

docs/opal.md
go.mod
go.sum
providers/opal/on_call_schedule.go
providers/opal/opal_provider.go

Update Opal provider to add support for latest version and on call schedules.
cc @jan-opal

feat: Allow importing on_call_schedule(s) and reviewer_stage(s) in Opal provider

---

docs/myrasec.md

New PR, as the old one went stale.

Corrects name of Myra resource

---

docs/aws.md
providers/aws/aws_provider.go
providers/aws/vpc_endpoint.go

Hi,
This PR implements AWS VPC Endpoint support, and resolves #572 and #1176.
I hope this small work is useful for the community.

Add Support for AWS VPC Endpoint (#572, #1176)

---

providers/opsgenie/opsgenie_provider.go
providers/opsgenie/opsgenie_service.go
providers/opsgenie/service.go

- uses same pattern as the "team" type and terminates when the number of services returned in a batch is 0

implemented first cut of the service type for opsgenie

---

providers/aws/lambda.go

Closes https://github.com/GoogleCloudPlatform/terraformer/issues/1599

fix: aws lambda: do not fail if only inline policy defined

---

.github/workflows/linter.yml
.github/workflows/release.yaml
.github/workflows/test.yml
go.mod

feat: use go1.22.0

---

docs/grafana.md

Fixed the wrong resource name in the example command

fix: grafana example

---

providers/okta/okta_provider.go

fix: add GetConfig for Okta provider
